(* AUTO-GENERATED LIFTER FILE *)

open Instruction_building_interface

let f_aarch64_vector_arithmetic_binary_element_mul_fp_sisd (type bitvector) (module I : IBI with type bitvector = bitvector) (v_enc : bitvector) (v_pc : bitvector) : unit = 
  if I.f_eq_bits (I.bigint_of_string "32") (I.f_and_bits (I.bigint_of_string "32") (v_enc) (I.from_bitsLit "00000000000000000000100000000000")) (I.from_bitsLit "00000000000000000000100000000000") then begin
    let v_index__1 = ref (I.mkBits (I.bigint_of_string "2") I.bigint_zero) in
    if I.f_eq_bits (I.bigint_of_string "32") (I.f_and_bits (I.bigint_of_string "32") (v_enc) (I.from_bitsLit "00000000010000000000000000000000")) (I.from_bitsLit "00000000000000000000000000000000") then begin
      v_index__1 := I.f_append_bits (I.bigint_of_string "1") (I.bigint_of_string "1") (I.extract_bits (v_enc) (I.bigint_of_string "11") (I.bigint_of_string "1")) (I.extract_bits (v_enc) (I.bigint_of_string "21") (I.bigint_of_string "1"))
    end else begin
      if I.f_eq_bits (I.bigint_of_string "32") (I.f_and_bits (I.bigint_of_string "32") (v_enc) (I.from_bitsLit "00000000011000000000000000000000")) (I.from_bitsLit "00000000010000000000000000000000") then begin
        v_index__1 := I.f_ZeroExtend (I.bigint_of_string "1") (I.bigint_of_string "2") (I.extract_bits (v_enc) (I.bigint_of_string "11") (I.bigint_of_string "1")) (I.bigint_of_string "2")
      end else begin
        failwith "unsupported"
      end
    end;
    if I.f_eq_bits (I.bigint_of_string "32") (I.f_and_bits (I.bigint_of_string "32") (v_enc) (I.from_bitsLit "00000000010000000000000000000000")) (I.from_bitsLit "00000000000000000000000000000000") then begin
      let v_result__1_copyprop = ref (I.undefined ()) in
      if I.f_eq_bits (I.bigint_of_string "32") (I.f_and_bits (I.bigint_of_string "32") (v_enc) (I.from_bitsLit "00100000000000000000000000000000")) (I.from_bitsLit "00100000000000000000000000000000") then begin
        let v_Exp19__2 = I.f_decl_bv ("Exp19__2") (I.bigint_of_string "32") in
        I.f_gen_store (v_Exp19__2) (I.f_gen_FPMulX (I.bigint_of_string "32") (I.f_gen_slice (I.f_gen_array_load (I.v__Z) (I.f_cvt_bits_uint (I.bigint_of_string "5") (I.extract_bits (v_enc) (I.bigint_of_string "5") (I.bigint_of_string "5")))) (I.bigint_of_string "0") (I.bigint_of_string "32")) (I.f_gen_slice (I.f_gen_slice (I.f_gen_lsr_bits (I.bigint_of_string "128") (I.bigint_of_string "16") (I.f_gen_array_load (I.v__Z) (I.f_cvt_bits_uint (I.bigint_of_string "5") (I.f_append_bits (I.bigint_of_string "1") (I.bigint_of_string "4") (I.extract_bits (v_enc) (I.bigint_of_string "20") (I.bigint_of_string "1")) (I.extract_bits (v_enc) (I.bigint_of_string "16") (I.bigint_of_string "4"))))) (I.f_gen_bit_lit (I.bigint_of_string "16") (I.f_ZeroExtend (I.bigint_of_string "8") (I.bigint_of_string "16") (I.f_mul_bits (I.bigint_of_string "8") (I.f_ZeroExtend (I.bigint_of_string "2") (I.bigint_of_string "8") (!v_index__1) (I.bigint_of_string "8")) (I.from_bitsLit "00100000")) (I.bigint_of_string "16")))) (I.bigint_of_string "0") (I.bigint_of_string "32")) (I.bigint_of_string "0") (I.bigint_of_string "32")) (I.f_gen_load (I.v_FPCR)));
        v_result__1_copyprop := I.f_gen_load (v_Exp19__2)
      end else begin
        let v_Exp23__2 = I.f_decl_bv ("Exp23__2") (I.bigint_of_string "32") in
        I.f_gen_store (v_Exp23__2) (I.f_gen_FPMul (I.bigint_of_string "32") (I.f_gen_slice (I.f_gen_array_load (I.v__Z) (I.f_cvt_bits_uint (I.bigint_of_string "5") (I.extract_bits (v_enc) (I.bigint_of_string "5") (I.bigint_of_string "5")))) (I.bigint_of_string "0") (I.bigint_of_string "32")) (I.f_gen_slice (I.f_gen_slice (I.f_gen_lsr_bits (I.bigint_of_string "128") (I.bigint_of_string "16") (I.f_gen_array_load (I.v__Z) (I.f_cvt_bits_uint (I.bigint_of_string "5") (I.f_append_bits (I.bigint_of_string "1") (I.bigint_of_string "4") (I.extract_bits (v_enc) (I.bigint_of_string "20") (I.bigint_of_string "1")) (I.extract_bits (v_enc) (I.bigint_of_string "16") (I.bigint_of_string "4"))))) (I.f_gen_bit_lit (I.bigint_of_string "16") (I.f_ZeroExtend (I.bigint_of_string "8") (I.bigint_of_string "16") (I.f_mul_bits (I.bigint_of_string "8") (I.f_ZeroExtend (I.bigint_of_string "2") (I.bigint_of_string "8") (!v_index__1) (I.bigint_of_string "8")) (I.from_bitsLit "00100000")) (I.bigint_of_string "16")))) (I.bigint_of_string "0") (I.bigint_of_string "32")) (I.bigint_of_string "0") (I.bigint_of_string "32")) (I.f_gen_load (I.v_FPCR)));
        v_result__1_copyprop := I.f_gen_load (v_Exp23__2)
      end;
      I.f_gen_array_store (I.v__Z) (I.f_cvt_bits_uint (I.bigint_of_string "5") (I.extract_bits (v_enc) (I.bigint_of_string "0") (I.bigint_of_string "5"))) (I.f_gen_ZeroExtend (I.bigint_of_string "32") (I.bigint_of_string "128") (!v_result__1_copyprop) (I.f_gen_int_lit (I.bigint_of_string "128")))
    end else begin
      let v_result__1_1_copyprop = ref (I.undefined ()) in
      assert ((true) && (I.f_sle_bits (I.bigint_of_string "32") (I.f_ZeroExtend (I.bigint_of_string "16") (I.bigint_of_string "32") (I.f_add_bits (I.bigint_of_string "16") (I.f_ZeroExtend (I.bigint_of_string "8") (I.bigint_of_string "16") (I.f_mul_bits (I.bigint_of_string "8") (I.f_ZeroExtend (I.bigint_of_string "2") (I.bigint_of_string "8") (!v_index__1) (I.bigint_of_string "8")) (I.from_bitsLit "01000000")) (I.bigint_of_string "16")) (I.from_bitsLit "0000000001000000")) (I.bigint_of_string "32")) (I.from_bitsLit "00000000000000000000000010000000")));
      if I.f_eq_bits (I.bigint_of_string "32") (I.f_and_bits (I.bigint_of_string "32") (v_enc) (I.from_bitsLit "00100000000000000000000000000000")) (I.from_bitsLit "00100000000000000000000000000000") then begin
        let v_Exp44__2 = I.f_decl_bv ("Exp44__2") (I.bigint_of_string "64") in
        I.f_gen_store (v_Exp44__2) (I.f_gen_FPMulX (I.bigint_of_string "64") (I.f_gen_slice (I.f_gen_array_load (I.v__Z) (I.f_cvt_bits_uint (I.bigint_of_string "5") (I.extract_bits (v_enc) (I.bigint_of_string "5") (I.bigint_of_string "5")))) (I.bigint_of_string "0") (I.bigint_of_string "64")) (I.f_gen_slice (I.f_gen_slice (I.f_gen_lsr_bits (I.bigint_of_string "128") (I.bigint_of_string "16") (I.f_gen_array_load (I.v__Z) (I.f_cvt_bits_uint (I.bigint_of_string "5") (I.f_append_bits (I.bigint_of_string "1") (I.bigint_of_string "4") (I.extract_bits (v_enc) (I.bigint_of_string "20") (I.bigint_of_string "1")) (I.extract_bits (v_enc) (I.bigint_of_string "16") (I.bigint_of_string "4"))))) (I.f_gen_bit_lit (I.bigint_of_string "16") (I.f_ZeroExtend (I.bigint_of_string "8") (I.bigint_of_string "16") (I.f_mul_bits (I.bigint_of_string "8") (I.f_ZeroExtend (I.bigint_of_string "2") (I.bigint_of_string "8") (!v_index__1) (I.bigint_of_string "8")) (I.from_bitsLit "01000000")) (I.bigint_of_string "16")))) (I.bigint_of_string "0") (I.bigint_of_string "64")) (I.bigint_of_string "0") (I.bigint_of_string "64")) (I.f_gen_load (I.v_FPCR)));
        v_result__1_1_copyprop := I.f_gen_load (v_Exp44__2)
      end else begin
        let v_Exp48__2 = I.f_decl_bv ("Exp48__2") (I.bigint_of_string "64") in
        I.f_gen_store (v_Exp48__2) (I.f_gen_FPMul (I.bigint_of_string "64") (I.f_gen_slice (I.f_gen_array_load (I.v__Z) (I.f_cvt_bits_uint (I.bigint_of_string "5") (I.extract_bits (v_enc) (I.bigint_of_string "5") (I.bigint_of_string "5")))) (I.bigint_of_string "0") (I.bigint_of_string "64")) (I.f_gen_slice (I.f_gen_slice (I.f_gen_lsr_bits (I.bigint_of_string "128") (I.bigint_of_string "16") (I.f_gen_array_load (I.v__Z) (I.f_cvt_bits_uint (I.bigint_of_string "5") (I.f_append_bits (I.bigint_of_string "1") (I.bigint_of_string "4") (I.extract_bits (v_enc) (I.bigint_of_string "20") (I.bigint_of_string "1")) (I.extract_bits (v_enc) (I.bigint_of_string "16") (I.bigint_of_string "4"))))) (I.f_gen_bit_lit (I.bigint_of_string "16") (I.f_ZeroExtend (I.bigint_of_string "8") (I.bigint_of_string "16") (I.f_mul_bits (I.bigint_of_string "8") (I.f_ZeroExtend (I.bigint_of_string "2") (I.bigint_of_string "8") (!v_index__1) (I.bigint_of_string "8")) (I.from_bitsLit "01000000")) (I.bigint_of_string "16")))) (I.bigint_of_string "0") (I.bigint_of_string "64")) (I.bigint_of_string "0") (I.bigint_of_string "64")) (I.f_gen_load (I.v_FPCR)));
        v_result__1_1_copyprop := I.f_gen_load (v_Exp48__2)
      end;
      I.f_gen_array_store (I.v__Z) (I.f_cvt_bits_uint (I.bigint_of_string "5") (I.extract_bits (v_enc) (I.bigint_of_string "0") (I.bigint_of_string "5"))) (I.f_gen_ZeroExtend (I.bigint_of_string "64") (I.bigint_of_string "128") (!v_result__1_1_copyprop) (I.f_gen_int_lit (I.bigint_of_string "128")))
    end
  end else begin
    let v_index__1_1 = ref (I.mkBits (I.bigint_of_string "2") I.bigint_zero) in
    if I.f_eq_bits (I.bigint_of_string "32") (I.f_and_bits (I.bigint_of_string "32") (v_enc) (I.from_bitsLit "00000000010000000000000000000000")) (I.from_bitsLit "00000000000000000000000000000000") then begin
      v_index__1_1 := I.f_append_bits (I.bigint_of_string "1") (I.bigint_of_string "1") (I.extract_bits (v_enc) (I.bigint_of_string "11") (I.bigint_of_string "1")) (I.extract_bits (v_enc) (I.bigint_of_string "21") (I.bigint_of_string "1"))
    end else begin
      if I.f_eq_bits (I.bigint_of_string "32") (I.f_and_bits (I.bigint_of_string "32") (v_enc) (I.from_bitsLit "00000000011000000000000000000000")) (I.from_bitsLit "00000000010000000000000000000000") then begin
        v_index__1_1 := I.f_ZeroExtend (I.bigint_of_string "1") (I.bigint_of_string "2") (I.extract_bits (v_enc) (I.bigint_of_string "11") (I.bigint_of_string "1")) (I.bigint_of_string "2")
      end else begin
        failwith "unsupported"
      end
    end;
    if I.f_eq_bits (I.bigint_of_string "32") (I.f_and_bits (I.bigint_of_string "32") (v_enc) (I.from_bitsLit "00000000010000000000000000000000")) (I.from_bitsLit "00000000000000000000000000000000") then begin
      let v_result__1_2_copyprop = ref (I.undefined ()) in
      assert ((true) && (I.f_sle_bits (I.bigint_of_string "16") (I.f_ZeroExtend (I.bigint_of_string "8") (I.bigint_of_string "16") (I.f_add_bits (I.bigint_of_string "8") (I.f_mul_bits (I.bigint_of_string "8") (I.f_ZeroExtend (I.bigint_of_string "2") (I.bigint_of_string "8") (!v_index__1_1) (I.bigint_of_string "8")) (I.from_bitsLit "00100000")) (I.from_bitsLit "00100000")) (I.bigint_of_string "16")) (I.from_bitsLit "0000000001000000")));
      if I.f_eq_bits (I.bigint_of_string "32") (I.f_and_bits (I.bigint_of_string "32") (v_enc) (I.from_bitsLit "00100000000000000000000000000000")) (I.from_bitsLit "00100000000000000000000000000000") then begin
        let v_Exp74__2 = I.f_decl_bv ("Exp74__2") (I.bigint_of_string "32") in
        I.f_gen_store (v_Exp74__2) (I.f_gen_FPMulX (I.bigint_of_string "32") (I.f_gen_slice (I.f_gen_array_load (I.v__Z) (I.f_cvt_bits_uint (I.bigint_of_string "5") (I.extract_bits (v_enc) (I.bigint_of_string "5") (I.bigint_of_string "5")))) (I.bigint_of_string "0") (I.bigint_of_string "32")) (I.f_gen_slice (I.f_gen_slice (I.f_gen_lsr_bits (I.bigint_of_string "128") (I.bigint_of_string "16") (I.f_gen_array_load (I.v__Z) (I.f_cvt_bits_uint (I.bigint_of_string "5") (I.f_append_bits (I.bigint_of_string "1") (I.bigint_of_string "4") (I.extract_bits (v_enc) (I.bigint_of_string "20") (I.bigint_of_string "1")) (I.extract_bits (v_enc) (I.bigint_of_string "16") (I.bigint_of_string "4"))))) (I.f_gen_bit_lit (I.bigint_of_string "16") (I.f_ZeroExtend (I.bigint_of_string "8") (I.bigint_of_string "16") (I.f_mul_bits (I.bigint_of_string "8") (I.f_ZeroExtend (I.bigint_of_string "2") (I.bigint_of_string "8") (!v_index__1_1) (I.bigint_of_string "8")) (I.from_bitsLit "00100000")) (I.bigint_of_string "16")))) (I.bigint_of_string "0") (I.bigint_of_string "32")) (I.bigint_of_string "0") (I.bigint_of_string "32")) (I.f_gen_load (I.v_FPCR)));
        v_result__1_2_copyprop := I.f_gen_load (v_Exp74__2)
      end else begin
        let v_Exp78__2 = I.f_decl_bv ("Exp78__2") (I.bigint_of_string "32") in
        I.f_gen_store (v_Exp78__2) (I.f_gen_FPMul (I.bigint_of_string "32") (I.f_gen_slice (I.f_gen_array_load (I.v__Z) (I.f_cvt_bits_uint (I.bigint_of_string "5") (I.extract_bits (v_enc) (I.bigint_of_string "5") (I.bigint_of_string "5")))) (I.bigint_of_string "0") (I.bigint_of_string "32")) (I.f_gen_slice (I.f_gen_slice (I.f_gen_lsr_bits (I.bigint_of_string "128") (I.bigint_of_string "16") (I.f_gen_array_load (I.v__Z) (I.f_cvt_bits_uint (I.bigint_of_string "5") (I.f_append_bits (I.bigint_of_string "1") (I.bigint_of_string "4") (I.extract_bits (v_enc) (I.bigint_of_string "20") (I.bigint_of_string "1")) (I.extract_bits (v_enc) (I.bigint_of_string "16") (I.bigint_of_string "4"))))) (I.f_gen_bit_lit (I.bigint_of_string "16") (I.f_ZeroExtend (I.bigint_of_string "8") (I.bigint_of_string "16") (I.f_mul_bits (I.bigint_of_string "8") (I.f_ZeroExtend (I.bigint_of_string "2") (I.bigint_of_string "8") (!v_index__1_1) (I.bigint_of_string "8")) (I.from_bitsLit "00100000")) (I.bigint_of_string "16")))) (I.bigint_of_string "0") (I.bigint_of_string "32")) (I.bigint_of_string "0") (I.bigint_of_string "32")) (I.f_gen_load (I.v_FPCR)));
        v_result__1_2_copyprop := I.f_gen_load (v_Exp78__2)
      end;
      I.f_gen_array_store (I.v__Z) (I.f_cvt_bits_uint (I.bigint_of_string "5") (I.extract_bits (v_enc) (I.bigint_of_string "0") (I.bigint_of_string "5"))) (I.f_gen_ZeroExtend (I.bigint_of_string "32") (I.bigint_of_string "128") (!v_result__1_2_copyprop) (I.f_gen_int_lit (I.bigint_of_string "128")))
    end else begin
      let v_result__1_3_copyprop = ref (I.undefined ()) in
      assert ((true) && (I.f_sle_bits (I.bigint_of_string "32") (I.f_ZeroExtend (I.bigint_of_string "16") (I.bigint_of_string "32") (I.f_add_bits (I.bigint_of_string "16") (I.f_ZeroExtend (I.bigint_of_string "8") (I.bigint_of_string "16") (I.f_mul_bits (I.bigint_of_string "8") (I.f_ZeroExtend (I.bigint_of_string "2") (I.bigint_of_string "8") (!v_index__1_1) (I.bigint_of_string "8")) (I.from_bitsLit "01000000")) (I.bigint_of_string "16")) (I.from_bitsLit "0000000001000000")) (I.bigint_of_string "32")) (I.from_bitsLit "00000000000000000000000001000000")));
      if I.f_eq_bits (I.bigint_of_string "32") (I.f_and_bits (I.bigint_of_string "32") (v_enc) (I.from_bitsLit "00100000000000000000000000000000")) (I.from_bitsLit "00100000000000000000000000000000") then begin
        let v_Exp99__2 = I.f_decl_bv ("Exp99__2") (I.bigint_of_string "64") in
        I.f_gen_store (v_Exp99__2) (I.f_gen_FPMulX (I.bigint_of_string "64") (I.f_gen_slice (I.f_gen_array_load (I.v__Z) (I.f_cvt_bits_uint (I.bigint_of_string "5") (I.extract_bits (v_enc) (I.bigint_of_string "5") (I.bigint_of_string "5")))) (I.bigint_of_string "0") (I.bigint_of_string "64")) (I.f_gen_slice (I.f_gen_slice (I.f_gen_lsr_bits (I.bigint_of_string "128") (I.bigint_of_string "16") (I.f_gen_array_load (I.v__Z) (I.f_cvt_bits_uint (I.bigint_of_string "5") (I.f_append_bits (I.bigint_of_string "1") (I.bigint_of_string "4") (I.extract_bits (v_enc) (I.bigint_of_string "20") (I.bigint_of_string "1")) (I.extract_bits (v_enc) (I.bigint_of_string "16") (I.bigint_of_string "4"))))) (I.f_gen_bit_lit (I.bigint_of_string "16") (I.f_ZeroExtend (I.bigint_of_string "8") (I.bigint_of_string "16") (I.f_mul_bits (I.bigint_of_string "8") (I.f_ZeroExtend (I.bigint_of_string "2") (I.bigint_of_string "8") (!v_index__1_1) (I.bigint_of_string "8")) (I.from_bitsLit "01000000")) (I.bigint_of_string "16")))) (I.bigint_of_string "0") (I.bigint_of_string "64")) (I.bigint_of_string "0") (I.bigint_of_string "64")) (I.f_gen_load (I.v_FPCR)));
        v_result__1_3_copyprop := I.f_gen_load (v_Exp99__2)
      end else begin
        let v_Exp103__2 = I.f_decl_bv ("Exp103__2") (I.bigint_of_string "64") in
        I.f_gen_store (v_Exp103__2) (I.f_gen_FPMul (I.bigint_of_string "64") (I.f_gen_slice (I.f_gen_array_load (I.v__Z) (I.f_cvt_bits_uint (I.bigint_of_string "5") (I.extract_bits (v_enc) (I.bigint_of_string "5") (I.bigint_of_string "5")))) (I.bigint_of_string "0") (I.bigint_of_string "64")) (I.f_gen_slice (I.f_gen_slice (I.f_gen_lsr_bits (I.bigint_of_string "128") (I.bigint_of_string "16") (I.f_gen_array_load (I.v__Z) (I.f_cvt_bits_uint (I.bigint_of_string "5") (I.f_append_bits (I.bigint_of_string "1") (I.bigint_of_string "4") (I.extract_bits (v_enc) (I.bigint_of_string "20") (I.bigint_of_string "1")) (I.extract_bits (v_enc) (I.bigint_of_string "16") (I.bigint_of_string "4"))))) (I.f_gen_bit_lit (I.bigint_of_string "16") (I.f_ZeroExtend (I.bigint_of_string "8") (I.bigint_of_string "16") (I.f_mul_bits (I.bigint_of_string "8") (I.f_ZeroExtend (I.bigint_of_string "2") (I.bigint_of_string "8") (!v_index__1_1) (I.bigint_of_string "8")) (I.from_bitsLit "01000000")) (I.bigint_of_string "16")))) (I.bigint_of_string "0") (I.bigint_of_string "64")) (I.bigint_of_string "0") (I.bigint_of_string "64")) (I.f_gen_load (I.v_FPCR)));
        v_result__1_3_copyprop := I.f_gen_load (v_Exp103__2)
      end;
      I.f_gen_array_store (I.v__Z) (I.f_cvt_bits_uint (I.bigint_of_string "5") (I.extract_bits (v_enc) (I.bigint_of_string "0") (I.bigint_of_string "5"))) (I.f_gen_ZeroExtend (I.bigint_of_string "64") (I.bigint_of_string "128") (!v_result__1_3_copyprop) (I.f_gen_int_lit (I.bigint_of_string "128")))
    end
  end

