(* AUTO-GENERATED LIFTER FILE *)

open Instruction_building_interface

let f_aarch64_vector_arithmetic_binary_element_mul_acc_fp16_sisd (type bitvector) (module I : IBI with type bitvector = bitvector) (v_enc : bitvector) (v_pc : bitvector) : unit = 
  if I.f_eq_bits (I.bigint_of_string "32") (I.f_and_bits (I.bigint_of_string "32") (v_enc) (I.from_bitsLit "00000000000000000000100000000000")) (I.from_bitsLit "00000000000000000000100000000000") then begin
    let v_result__1_copyprop = ref (I.undefined ()) in
    if I.f_eq_bits (I.bigint_of_string "32") (I.f_and_bits (I.bigint_of_string "32") (v_enc) (I.from_bitsLit "00000000000000000100000000000000")) (I.from_bitsLit "00000000000000000100000000000000") then begin
      let v_Exp22__2 = I.f_decl_bv ("Exp22__2") (I.bigint_of_string "16") in
      I.f_gen_store (v_Exp22__2) (I.f_gen_FPMulAdd (I.bigint_of_string "16") (I.f_gen_slice (I.f_gen_array_load (I.v__Z) (I.f_cvt_bits_uint (I.bigint_of_string "5") (I.extract_bits (v_enc) (I.bigint_of_string "0") (I.bigint_of_string "5")))) (I.bigint_of_string "0") (I.bigint_of_string "16")) (I.f_gen_append_bits (I.bigint_of_string "1") (I.bigint_of_string "15") (I.f_gen_not_bits (I.bigint_of_string "1") (I.f_gen_slice (I.f_gen_array_load (I.v__Z) (I.f_cvt_bits_uint (I.bigint_of_string "5") (I.extract_bits (v_enc) (I.bigint_of_string "5") (I.bigint_of_string "5")))) (I.bigint_of_string "15") (I.bigint_of_string "1"))) (I.f_gen_slice (I.f_gen_array_load (I.v__Z) (I.f_cvt_bits_uint (I.bigint_of_string "5") (I.extract_bits (v_enc) (I.bigint_of_string "5") (I.bigint_of_string "5")))) (I.bigint_of_string "0") (I.bigint_of_string "15"))) (I.f_gen_slice (I.f_gen_slice (I.f_gen_lsr_bits (I.bigint_of_string "128") (I.bigint_of_string "16") (I.f_gen_array_load (I.v__Z) (I.f_cvt_bits_uint (I.bigint_of_string "4") (I.extract_bits (v_enc) (I.bigint_of_string "16") (I.bigint_of_string "4")))) (I.f_gen_bit_lit (I.bigint_of_string "16") (I.f_ZeroExtend (I.bigint_of_string "8") (I.bigint_of_string "16") (I.f_mul_bits (I.bigint_of_string "8") (I.f_ZeroExtend (I.bigint_of_string "3") (I.bigint_of_string "8") (I.f_append_bits (I.bigint_of_string "2") (I.bigint_of_string "1") (I.f_append_bits (I.bigint_of_string "1") (I.bigint_of_string "1") (I.extract_bits (v_enc) (I.bigint_of_string "11") (I.bigint_of_string "1")) (I.extract_bits (v_enc) (I.bigint_of_string "21") (I.bigint_of_string "1"))) (I.extract_bits (v_enc) (I.bigint_of_string "20") (I.bigint_of_string "1"))) (I.bigint_of_string "8")) (I.from_bitsLit "00010000")) (I.bigint_of_string "16")))) (I.bigint_of_string "0") (I.bigint_of_string "16")) (I.bigint_of_string "0") (I.bigint_of_string "16")) (I.f_gen_load (I.v_FPCR)));
      v_result__1_copyprop := I.f_gen_load (v_Exp22__2)
    end else begin
      let v_Exp27__2 = I.f_decl_bv ("Exp27__2") (I.bigint_of_string "16") in
      I.f_gen_store (v_Exp27__2) (I.f_gen_FPMulAdd (I.bigint_of_string "16") (I.f_gen_slice (I.f_gen_array_load (I.v__Z) (I.f_cvt_bits_uint (I.bigint_of_string "5") (I.extract_bits (v_enc) (I.bigint_of_string "0") (I.bigint_of_string "5")))) (I.bigint_of_string "0") (I.bigint_of_string "16")) (I.f_gen_slice (I.f_gen_array_load (I.v__Z) (I.f_cvt_bits_uint (I.bigint_of_string "5") (I.extract_bits (v_enc) (I.bigint_of_string "5") (I.bigint_of_string "5")))) (I.bigint_of_string "0") (I.bigint_of_string "16")) (I.f_gen_slice (I.f_gen_slice (I.f_gen_lsr_bits (I.bigint_of_string "128") (I.bigint_of_string "16") (I.f_gen_array_load (I.v__Z) (I.f_cvt_bits_uint (I.bigint_of_string "4") (I.extract_bits (v_enc) (I.bigint_of_string "16") (I.bigint_of_string "4")))) (I.f_gen_bit_lit (I.bigint_of_string "16") (I.f_ZeroExtend (I.bigint_of_string "8") (I.bigint_of_string "16") (I.f_mul_bits (I.bigint_of_string "8") (I.f_ZeroExtend (I.bigint_of_string "3") (I.bigint_of_string "8") (I.f_append_bits (I.bigint_of_string "2") (I.bigint_of_string "1") (I.f_append_bits (I.bigint_of_string "1") (I.bigint_of_string "1") (I.extract_bits (v_enc) (I.bigint_of_string "11") (I.bigint_of_string "1")) (I.extract_bits (v_enc) (I.bigint_of_string "21") (I.bigint_of_string "1"))) (I.extract_bits (v_enc) (I.bigint_of_string "20") (I.bigint_of_string "1"))) (I.bigint_of_string "8")) (I.from_bitsLit "00010000")) (I.bigint_of_string "16")))) (I.bigint_of_string "0") (I.bigint_of_string "16")) (I.bigint_of_string "0") (I.bigint_of_string "16")) (I.f_gen_load (I.v_FPCR)));
      v_result__1_copyprop := I.f_gen_load (v_Exp27__2)
    end;
    I.f_gen_array_store (I.v__Z) (I.f_cvt_bits_uint (I.bigint_of_string "5") (I.extract_bits (v_enc) (I.bigint_of_string "0") (I.bigint_of_string "5"))) (I.f_gen_ZeroExtend (I.bigint_of_string "16") (I.bigint_of_string "128") (!v_result__1_copyprop) (I.f_gen_int_lit (I.bigint_of_string "128")))
  end else begin
    let v_result__1_1_copyprop = ref (I.undefined ()) in
    assert ((true) && (I.f_sle_bits (I.bigint_of_string "16") (I.f_ZeroExtend (I.bigint_of_string "8") (I.bigint_of_string "16") (I.f_add_bits (I.bigint_of_string "8") (I.f_mul_bits (I.bigint_of_string "8") (I.f_ZeroExtend (I.bigint_of_string "3") (I.bigint_of_string "8") (I.f_append_bits (I.bigint_of_string "2") (I.bigint_of_string "1") (I.f_append_bits (I.bigint_of_string "1") (I.bigint_of_string "1") (I.extract_bits (v_enc) (I.bigint_of_string "11") (I.bigint_of_string "1")) (I.extract_bits (v_enc) (I.bigint_of_string "21") (I.bigint_of_string "1"))) (I.extract_bits (v_enc) (I.bigint_of_string "20") (I.bigint_of_string "1"))) (I.bigint_of_string "8")) (I.from_bitsLit "00010000")) (I.from_bitsLit "00010000")) (I.bigint_of_string "16")) (I.from_bitsLit "0000000001000000")));
    if I.f_eq_bits (I.bigint_of_string "32") (I.f_and_bits (I.bigint_of_string "32") (v_enc) (I.from_bitsLit "00000000000000000100000000000000")) (I.from_bitsLit "00000000000000000100000000000000") then begin
      let v_Exp55__2 = I.f_decl_bv ("Exp55__2") (I.bigint_of_string "16") in
      I.f_gen_store (v_Exp55__2) (I.f_gen_FPMulAdd (I.bigint_of_string "16") (I.f_gen_slice (I.f_gen_array_load (I.v__Z) (I.f_cvt_bits_uint (I.bigint_of_string "5") (I.extract_bits (v_enc) (I.bigint_of_string "0") (I.bigint_of_string "5")))) (I.bigint_of_string "0") (I.bigint_of_string "16")) (I.f_gen_append_bits (I.bigint_of_string "1") (I.bigint_of_string "15") (I.f_gen_not_bits (I.bigint_of_string "1") (I.f_gen_slice (I.f_gen_array_load (I.v__Z) (I.f_cvt_bits_uint (I.bigint_of_string "5") (I.extract_bits (v_enc) (I.bigint_of_string "5") (I.bigint_of_string "5")))) (I.bigint_of_string "15") (I.bigint_of_string "1"))) (I.f_gen_slice (I.f_gen_array_load (I.v__Z) (I.f_cvt_bits_uint (I.bigint_of_string "5") (I.extract_bits (v_enc) (I.bigint_of_string "5") (I.bigint_of_string "5")))) (I.bigint_of_string "0") (I.bigint_of_string "15"))) (I.f_gen_slice (I.f_gen_slice (I.f_gen_lsr_bits (I.bigint_of_string "128") (I.bigint_of_string "16") (I.f_gen_array_load (I.v__Z) (I.f_cvt_bits_uint (I.bigint_of_string "4") (I.extract_bits (v_enc) (I.bigint_of_string "16") (I.bigint_of_string "4")))) (I.f_gen_bit_lit (I.bigint_of_string "16") (I.f_ZeroExtend (I.bigint_of_string "8") (I.bigint_of_string "16") (I.f_mul_bits (I.bigint_of_string "8") (I.f_ZeroExtend (I.bigint_of_string "3") (I.bigint_of_string "8") (I.f_append_bits (I.bigint_of_string "2") (I.bigint_of_string "1") (I.f_append_bits (I.bigint_of_string "1") (I.bigint_of_string "1") (I.extract_bits (v_enc) (I.bigint_of_string "11") (I.bigint_of_string "1")) (I.extract_bits (v_enc) (I.bigint_of_string "21") (I.bigint_of_string "1"))) (I.extract_bits (v_enc) (I.bigint_of_string "20") (I.bigint_of_string "1"))) (I.bigint_of_string "8")) (I.from_bitsLit "00010000")) (I.bigint_of_string "16")))) (I.bigint_of_string "0") (I.bigint_of_string "16")) (I.bigint_of_string "0") (I.bigint_of_string "16")) (I.f_gen_load (I.v_FPCR)));
      v_result__1_1_copyprop := I.f_gen_load (v_Exp55__2)
    end else begin
      let v_Exp60__2 = I.f_decl_bv ("Exp60__2") (I.bigint_of_string "16") in
      I.f_gen_store (v_Exp60__2) (I.f_gen_FPMulAdd (I.bigint_of_string "16") (I.f_gen_slice (I.f_gen_array_load (I.v__Z) (I.f_cvt_bits_uint (I.bigint_of_string "5") (I.extract_bits (v_enc) (I.bigint_of_string "0") (I.bigint_of_string "5")))) (I.bigint_of_string "0") (I.bigint_of_string "16")) (I.f_gen_slice (I.f_gen_array_load (I.v__Z) (I.f_cvt_bits_uint (I.bigint_of_string "5") (I.extract_bits (v_enc) (I.bigint_of_string "5") (I.bigint_of_string "5")))) (I.bigint_of_string "0") (I.bigint_of_string "16")) (I.f_gen_slice (I.f_gen_slice (I.f_gen_lsr_bits (I.bigint_of_string "128") (I.bigint_of_string "16") (I.f_gen_array_load (I.v__Z) (I.f_cvt_bits_uint (I.bigint_of_string "4") (I.extract_bits (v_enc) (I.bigint_of_string "16") (I.bigint_of_string "4")))) (I.f_gen_bit_lit (I.bigint_of_string "16") (I.f_ZeroExtend (I.bigint_of_string "8") (I.bigint_of_string "16") (I.f_mul_bits (I.bigint_of_string "8") (I.f_ZeroExtend (I.bigint_of_string "3") (I.bigint_of_string "8") (I.f_append_bits (I.bigint_of_string "2") (I.bigint_of_string "1") (I.f_append_bits (I.bigint_of_string "1") (I.bigint_of_string "1") (I.extract_bits (v_enc) (I.bigint_of_string "11") (I.bigint_of_string "1")) (I.extract_bits (v_enc) (I.bigint_of_string "21") (I.bigint_of_string "1"))) (I.extract_bits (v_enc) (I.bigint_of_string "20") (I.bigint_of_string "1"))) (I.bigint_of_string "8")) (I.from_bitsLit "00010000")) (I.bigint_of_string "16")))) (I.bigint_of_string "0") (I.bigint_of_string "16")) (I.bigint_of_string "0") (I.bigint_of_string "16")) (I.f_gen_load (I.v_FPCR)));
      v_result__1_1_copyprop := I.f_gen_load (v_Exp60__2)
    end;
    I.f_gen_array_store (I.v__Z) (I.f_cvt_bits_uint (I.bigint_of_string "5") (I.extract_bits (v_enc) (I.bigint_of_string "0") (I.bigint_of_string "5"))) (I.f_gen_ZeroExtend (I.bigint_of_string "16") (I.bigint_of_string "128") (!v_result__1_1_copyprop) (I.f_gen_int_lit (I.bigint_of_string "128")))
  end

