(* AUTO-GENERATED LIFTER FILE *)

open Instruction_building_interface

let f_aarch64_vector_arithmetic_binary_element_mul_acc_mul_norounding_i_lower (type bitvector) (module I : IBI with type bitvector = bitvector) (v_enc : bitvector) (v_pc : bitvector) : unit = 
  if I.f_eq_bits (I.bigint_of_string "32") (I.f_and_bits (I.bigint_of_string "32") (v_enc) (I.from_bitsLit "01000000000000000000000000000000")) (I.from_bitsLit "01000000000000000000000000000000") then begin
    let v_Exp12__3 = I.f_decl_bv ("Exp12__3") (I.bigint_of_string "128") in
    I.f_gen_store (v_Exp12__3) (I.f_gen_array_load (I.v__Z) (I.f_cvt_bits_uint (I.bigint_of_string "5") (I.extract_bits (v_enc) (I.bigint_of_string "5") (I.bigint_of_string "5"))));
    let v_Exp15__2 = I.f_decl_bv ("Exp15__2") (I.bigint_of_string "128") in
    I.f_gen_store (v_Exp15__2) (I.f_gen_array_load (I.v__Z) (I.f_cvt_bits_uint (I.bigint_of_string "5") (I.f_append_bits (I.bigint_of_string "1") (I.bigint_of_string "4") (I.from_bitsLit "0") (I.extract_bits (v_enc) (I.bigint_of_string "16") (I.bigint_of_string "4")))));
    let v_Exp18__2 = I.f_decl_bv ("Exp18__2") (I.bigint_of_string "128") in
    I.f_gen_store (v_Exp18__2) (I.f_gen_array_load (I.v__Z) (I.f_cvt_bits_uint (I.bigint_of_string "5") (I.extract_bits (v_enc) (I.bigint_of_string "0") (I.bigint_of_string "5"))));
    let v_result__1 = I.f_decl_bv ("result__1") (I.bigint_of_string "128") in
    if I.f_eq_bits (I.bigint_of_string "32") (I.f_and_bits (I.bigint_of_string "32") (v_enc) (I.from_bitsLit "00000000000000000100000000000000")) (I.from_bitsLit "00000000000000000100000000000000") then begin
      let v_Exp26__2 = I.f_decl_bv ("Exp26__2") (I.bigint_of_string "32") in
      I.f_gen_store (v_Exp26__2) (I.f_gen_FPMulAddH (I.bigint_of_string "32") (I.f_gen_slice (I.f_gen_array_load (I.v__Z) (I.f_cvt_bits_uint (I.bigint_of_string "5") (I.extract_bits (v_enc) (I.bigint_of_string "0") (I.bigint_of_string "5")))) (I.bigint_of_string "0") (I.bigint_of_string "32")) (I.f_gen_append_bits (I.bigint_of_string "1") (I.bigint_of_string "15") (I.f_gen_not_bits (I.bigint_of_string "1") (I.f_gen_slice (I.f_gen_array_load (I.v__Z) (I.f_cvt_bits_uint (I.bigint_of_string "5") (I.extract_bits (v_enc) (I.bigint_of_string "5") (I.bigint_of_string "5")))) (I.bigint_of_string "15") (I.bigint_of_string "1"))) (I.f_gen_slice (I.f_gen_array_load (I.v__Z) (I.f_cvt_bits_uint (I.bigint_of_string "5") (I.extract_bits (v_enc) (I.bigint_of_string "5") (I.bigint_of_string "5")))) (I.bigint_of_string "0") (I.bigint_of_string "15"))) (I.f_gen_slice (I.f_gen_slice (I.f_gen_lsr_bits (I.bigint_of_string "128") (I.bigint_of_string "16") (I.f_gen_array_load (I.v__Z) (I.f_cvt_bits_uint (I.bigint_of_string "5") (I.f_append_bits (I.bigint_of_string "1") (I.bigint_of_string "4") (I.from_bitsLit "0") (I.extract_bits (v_enc) (I.bigint_of_string "16") (I.bigint_of_string "4"))))) (I.f_gen_bit_lit (I.bigint_of_string "16") (I.f_ZeroExtend (I.bigint_of_string "8") (I.bigint_of_string "16") (I.f_mul_bits (I.bigint_of_string "8") (I.f_ZeroExtend (I.bigint_of_string "3") (I.bigint_of_string "8") (I.f_append_bits (I.bigint_of_string "2") (I.bigint_of_string "1") (I.f_append_bits (I.bigint_of_string "1") (I.bigint_of_string "1") (I.extract_bits (v_enc) (I.bigint_of_string "11") (I.bigint_of_string "1")) (I.extract_bits (v_enc) (I.bigint_of_string "21") (I.bigint_of_string "1"))) (I.extract_bits (v_enc) (I.bigint_of_string "20") (I.bigint_of_string "1"))) (I.bigint_of_string "8")) (I.from_bitsLit "00010000")) (I.bigint_of_string "16")))) (I.bigint_of_string "0") (I.bigint_of_string "16")) (I.bigint_of_string "0") (I.bigint_of_string "16")) (I.f_gen_load (I.v_FPCR)));
      I.f_gen_store (v_result__1) (I.f_gen_append_bits (I.bigint_of_string "96") (I.bigint_of_string "32") (I.f_gen_slice (I.f_gen_load (v_result__1)) (I.bigint_of_string "32") (I.bigint_of_string "96")) (I.f_gen_load (v_Exp26__2)))
    end else begin
      let v_Exp31__2 = I.f_decl_bv ("Exp31__2") (I.bigint_of_string "32") in
      I.f_gen_store (v_Exp31__2) (I.f_gen_FPMulAddH (I.bigint_of_string "32") (I.f_gen_slice (I.f_gen_array_load (I.v__Z) (I.f_cvt_bits_uint (I.bigint_of_string "5") (I.extract_bits (v_enc) (I.bigint_of_string "0") (I.bigint_of_string "5")))) (I.bigint_of_string "0") (I.bigint_of_string "32")) (I.f_gen_slice (I.f_gen_array_load (I.v__Z) (I.f_cvt_bits_uint (I.bigint_of_string "5") (I.extract_bits (v_enc) (I.bigint_of_string "5") (I.bigint_of_string "5")))) (I.bigint_of_string "0") (I.bigint_of_string "16")) (I.f_gen_slice (I.f_gen_slice (I.f_gen_lsr_bits (I.bigint_of_string "128") (I.bigint_of_string "16") (I.f_gen_array_load (I.v__Z) (I.f_cvt_bits_uint (I.bigint_of_string "5") (I.f_append_bits (I.bigint_of_string "1") (I.bigint_of_string "4") (I.from_bitsLit "0") (I.extract_bits (v_enc) (I.bigint_of_string "16") (I.bigint_of_string "4"))))) (I.f_gen_bit_lit (I.bigint_of_string "16") (I.f_ZeroExtend (I.bigint_of_string "8") (I.bigint_of_string "16") (I.f_mul_bits (I.bigint_of_string "8") (I.f_ZeroExtend (I.bigint_of_string "3") (I.bigint_of_string "8") (I.f_append_bits (I.bigint_of_string "2") (I.bigint_of_string "1") (I.f_append_bits (I.bigint_of_string "1") (I.bigint_of_string "1") (I.extract_bits (v_enc) (I.bigint_of_string "11") (I.bigint_of_string "1")) (I.extract_bits (v_enc) (I.bigint_of_string "21") (I.bigint_of_string "1"))) (I.extract_bits (v_enc) (I.bigint_of_string "20") (I.bigint_of_string "1"))) (I.bigint_of_string "8")) (I.from_bitsLit "00010000")) (I.bigint_of_string "16")))) (I.bigint_of_string "0") (I.bigint_of_string "16")) (I.bigint_of_string "0") (I.bigint_of_string "16")) (I.f_gen_load (I.v_FPCR)));
      I.f_gen_store (v_result__1) (I.f_gen_append_bits (I.bigint_of_string "96") (I.bigint_of_string "32") (I.f_gen_slice (I.f_gen_load (v_result__1)) (I.bigint_of_string "32") (I.bigint_of_string "96")) (I.f_gen_load (v_Exp31__2)))
    end;
    if I.f_eq_bits (I.bigint_of_string "32") (I.f_and_bits (I.bigint_of_string "32") (v_enc) (I.from_bitsLit "00000000000000000100000000000000")) (I.from_bitsLit "00000000000000000100000000000000") then begin
      let v_Exp38__2 = I.f_decl_bv ("Exp38__2") (I.bigint_of_string "32") in
      I.f_gen_store (v_Exp38__2) (I.f_gen_FPMulAddH (I.bigint_of_string "32") (I.f_gen_slice (I.f_gen_load (v_Exp18__2)) (I.bigint_of_string "32") (I.bigint_of_string "32")) (I.f_gen_append_bits (I.bigint_of_string "1") (I.bigint_of_string "15") (I.f_gen_not_bits (I.bigint_of_string "1") (I.f_gen_slice (I.f_gen_load (v_Exp12__3)) (I.bigint_of_string "31") (I.bigint_of_string "1"))) (I.f_gen_slice (I.f_gen_load (v_Exp12__3)) (I.bigint_of_string "16") (I.bigint_of_string "15"))) (I.f_gen_slice (I.f_gen_slice (I.f_gen_lsr_bits (I.bigint_of_string "128") (I.bigint_of_string "16") (I.f_gen_load (v_Exp15__2)) (I.f_gen_bit_lit (I.bigint_of_string "16") (I.f_ZeroExtend (I.bigint_of_string "8") (I.bigint_of_string "16") (I.f_mul_bits (I.bigint_of_string "8") (I.f_ZeroExtend (I.bigint_of_string "3") (I.bigint_of_string "8") (I.f_append_bits (I.bigint_of_string "2") (I.bigint_of_string "1") (I.f_append_bits (I.bigint_of_string "1") (I.bigint_of_string "1") (I.extract_bits (v_enc) (I.bigint_of_string "11") (I.bigint_of_string "1")) (I.extract_bits (v_enc) (I.bigint_of_string "21") (I.bigint_of_string "1"))) (I.extract_bits (v_enc) (I.bigint_of_string "20") (I.bigint_of_string "1"))) (I.bigint_of_string "8")) (I.from_bitsLit "00010000")) (I.bigint_of_string "16")))) (I.bigint_of_string "0") (I.bigint_of_string "16")) (I.bigint_of_string "0") (I.bigint_of_string "16")) (I.f_gen_load (I.v_FPCR)));
      I.f_gen_store (v_result__1) (I.f_gen_append_bits (I.bigint_of_string "64") (I.bigint_of_string "64") (I.f_gen_slice (I.f_gen_load (v_result__1)) (I.bigint_of_string "64") (I.bigint_of_string "64")) (I.f_gen_append_bits (I.bigint_of_string "32") (I.bigint_of_string "32") (I.f_gen_load (v_Exp38__2)) (I.f_gen_slice (I.f_gen_load (v_result__1)) (I.bigint_of_string "0") (I.bigint_of_string "32"))))
    end else begin
      let v_Exp43__2 = I.f_decl_bv ("Exp43__2") (I.bigint_of_string "32") in
      I.f_gen_store (v_Exp43__2) (I.f_gen_FPMulAddH (I.bigint_of_string "32") (I.f_gen_slice (I.f_gen_load (v_Exp18__2)) (I.bigint_of_string "32") (I.bigint_of_string "32")) (I.f_gen_slice (I.f_gen_load (v_Exp12__3)) (I.bigint_of_string "16") (I.bigint_of_string "16")) (I.f_gen_slice (I.f_gen_slice (I.f_gen_lsr_bits (I.bigint_of_string "128") (I.bigint_of_string "16") (I.f_gen_load (v_Exp15__2)) (I.f_gen_bit_lit (I.bigint_of_string "16") (I.f_ZeroExtend (I.bigint_of_string "8") (I.bigint_of_string "16") (I.f_mul_bits (I.bigint_of_string "8") (I.f_ZeroExtend (I.bigint_of_string "3") (I.bigint_of_string "8") (I.f_append_bits (I.bigint_of_string "2") (I.bigint_of_string "1") (I.f_append_bits (I.bigint_of_string "1") (I.bigint_of_string "1") (I.extract_bits (v_enc) (I.bigint_of_string "11") (I.bigint_of_string "1")) (I.extract_bits (v_enc) (I.bigint_of_string "21") (I.bigint_of_string "1"))) (I.extract_bits (v_enc) (I.bigint_of_string "20") (I.bigint_of_string "1"))) (I.bigint_of_string "8")) (I.from_bitsLit "00010000")) (I.bigint_of_string "16")))) (I.bigint_of_string "0") (I.bigint_of_string "16")) (I.bigint_of_string "0") (I.bigint_of_string "16")) (I.f_gen_load (I.v_FPCR)));
      I.f_gen_store (v_result__1) (I.f_gen_append_bits (I.bigint_of_string "64") (I.bigint_of_string "64") (I.f_gen_slice (I.f_gen_load (v_result__1)) (I.bigint_of_string "64") (I.bigint_of_string "64")) (I.f_gen_append_bits (I.bigint_of_string "32") (I.bigint_of_string "32") (I.f_gen_load (v_Exp43__2)) (I.f_gen_slice (I.f_gen_load (v_result__1)) (I.bigint_of_string "0") (I.bigint_of_string "32"))))
    end;
    if I.f_eq_bits (I.bigint_of_string "32") (I.f_and_bits (I.bigint_of_string "32") (v_enc) (I.from_bitsLit "00000000000000000100000000000000")) (I.from_bitsLit "00000000000000000100000000000000") then begin
      let v_Exp50__2 = I.f_decl_bv ("Exp50__2") (I.bigint_of_string "32") in
      I.f_gen_store (v_Exp50__2) (I.f_gen_FPMulAddH (I.bigint_of_string "32") (I.f_gen_slice (I.f_gen_load (v_Exp18__2)) (I.bigint_of_string "64") (I.bigint_of_string "32")) (I.f_gen_append_bits (I.bigint_of_string "1") (I.bigint_of_string "15") (I.f_gen_not_bits (I.bigint_of_string "1") (I.f_gen_slice (I.f_gen_load (v_Exp12__3)) (I.bigint_of_string "47") (I.bigint_of_string "1"))) (I.f_gen_slice (I.f_gen_load (v_Exp12__3)) (I.bigint_of_string "32") (I.bigint_of_string "15"))) (I.f_gen_slice (I.f_gen_slice (I.f_gen_lsr_bits (I.bigint_of_string "128") (I.bigint_of_string "16") (I.f_gen_load (v_Exp15__2)) (I.f_gen_bit_lit (I.bigint_of_string "16") (I.f_ZeroExtend (I.bigint_of_string "8") (I.bigint_of_string "16") (I.f_mul_bits (I.bigint_of_string "8") (I.f_ZeroExtend (I.bigint_of_string "3") (I.bigint_of_string "8") (I.f_append_bits (I.bigint_of_string "2") (I.bigint_of_string "1") (I.f_append_bits (I.bigint_of_string "1") (I.bigint_of_string "1") (I.extract_bits (v_enc) (I.bigint_of_string "11") (I.bigint_of_string "1")) (I.extract_bits (v_enc) (I.bigint_of_string "21") (I.bigint_of_string "1"))) (I.extract_bits (v_enc) (I.bigint_of_string "20") (I.bigint_of_string "1"))) (I.bigint_of_string "8")) (I.from_bitsLit "00010000")) (I.bigint_of_string "16")))) (I.bigint_of_string "0") (I.bigint_of_string "16")) (I.bigint_of_string "0") (I.bigint_of_string "16")) (I.f_gen_load (I.v_FPCR)));
      I.f_gen_store (v_result__1) (I.f_gen_append_bits (I.bigint_of_string "32") (I.bigint_of_string "96") (I.f_gen_slice (I.f_gen_load (v_result__1)) (I.bigint_of_string "96") (I.bigint_of_string "32")) (I.f_gen_append_bits (I.bigint_of_string "32") (I.bigint_of_string "64") (I.f_gen_load (v_Exp50__2)) (I.f_gen_slice (I.f_gen_load (v_result__1)) (I.bigint_of_string "0") (I.bigint_of_string "64"))))
    end else begin
      let v_Exp55__2 = I.f_decl_bv ("Exp55__2") (I.bigint_of_string "32") in
      I.f_gen_store (v_Exp55__2) (I.f_gen_FPMulAddH (I.bigint_of_string "32") (I.f_gen_slice (I.f_gen_load (v_Exp18__2)) (I.bigint_of_string "64") (I.bigint_of_string "32")) (I.f_gen_slice (I.f_gen_load (v_Exp12__3)) (I.bigint_of_string "32") (I.bigint_of_string "16")) (I.f_gen_slice (I.f_gen_slice (I.f_gen_lsr_bits (I.bigint_of_string "128") (I.bigint_of_string "16") (I.f_gen_load (v_Exp15__2)) (I.f_gen_bit_lit (I.bigint_of_string "16") (I.f_ZeroExtend (I.bigint_of_string "8") (I.bigint_of_string "16") (I.f_mul_bits (I.bigint_of_string "8") (I.f_ZeroExtend (I.bigint_of_string "3") (I.bigint_of_string "8") (I.f_append_bits (I.bigint_of_string "2") (I.bigint_of_string "1") (I.f_append_bits (I.bigint_of_string "1") (I.bigint_of_string "1") (I.extract_bits (v_enc) (I.bigint_of_string "11") (I.bigint_of_string "1")) (I.extract_bits (v_enc) (I.bigint_of_string "21") (I.bigint_of_string "1"))) (I.extract_bits (v_enc) (I.bigint_of_string "20") (I.bigint_of_string "1"))) (I.bigint_of_string "8")) (I.from_bitsLit "00010000")) (I.bigint_of_string "16")))) (I.bigint_of_string "0") (I.bigint_of_string "16")) (I.bigint_of_string "0") (I.bigint_of_string "16")) (I.f_gen_load (I.v_FPCR)));
      I.f_gen_store (v_result__1) (I.f_gen_append_bits (I.bigint_of_string "32") (I.bigint_of_string "96") (I.f_gen_slice (I.f_gen_load (v_result__1)) (I.bigint_of_string "96") (I.bigint_of_string "32")) (I.f_gen_append_bits (I.bigint_of_string "32") (I.bigint_of_string "64") (I.f_gen_load (v_Exp55__2)) (I.f_gen_slice (I.f_gen_load (v_result__1)) (I.bigint_of_string "0") (I.bigint_of_string "64"))))
    end;
    if I.f_eq_bits (I.bigint_of_string "32") (I.f_and_bits (I.bigint_of_string "32") (v_enc) (I.from_bitsLit "00000000000000000100000000000000")) (I.from_bitsLit "00000000000000000100000000000000") then begin
      let v_Exp62__2 = I.f_decl_bv ("Exp62__2") (I.bigint_of_string "32") in
      I.f_gen_store (v_Exp62__2) (I.f_gen_FPMulAddH (I.bigint_of_string "32") (I.f_gen_slice (I.f_gen_load (v_Exp18__2)) (I.bigint_of_string "96") (I.bigint_of_string "32")) (I.f_gen_append_bits (I.bigint_of_string "1") (I.bigint_of_string "15") (I.f_gen_not_bits (I.bigint_of_string "1") (I.f_gen_slice (I.f_gen_load (v_Exp12__3)) (I.bigint_of_string "63") (I.bigint_of_string "1"))) (I.f_gen_slice (I.f_gen_load (v_Exp12__3)) (I.bigint_of_string "48") (I.bigint_of_string "15"))) (I.f_gen_slice (I.f_gen_slice (I.f_gen_lsr_bits (I.bigint_of_string "128") (I.bigint_of_string "16") (I.f_gen_load (v_Exp15__2)) (I.f_gen_bit_lit (I.bigint_of_string "16") (I.f_ZeroExtend (I.bigint_of_string "8") (I.bigint_of_string "16") (I.f_mul_bits (I.bigint_of_string "8") (I.f_ZeroExtend (I.bigint_of_string "3") (I.bigint_of_string "8") (I.f_append_bits (I.bigint_of_string "2") (I.bigint_of_string "1") (I.f_append_bits (I.bigint_of_string "1") (I.bigint_of_string "1") (I.extract_bits (v_enc) (I.bigint_of_string "11") (I.bigint_of_string "1")) (I.extract_bits (v_enc) (I.bigint_of_string "21") (I.bigint_of_string "1"))) (I.extract_bits (v_enc) (I.bigint_of_string "20") (I.bigint_of_string "1"))) (I.bigint_of_string "8")) (I.from_bitsLit "00010000")) (I.bigint_of_string "16")))) (I.bigint_of_string "0") (I.bigint_of_string "16")) (I.bigint_of_string "0") (I.bigint_of_string "16")) (I.f_gen_load (I.v_FPCR)));
      I.f_gen_store (v_result__1) (I.f_gen_append_bits (I.bigint_of_string "32") (I.bigint_of_string "96") (I.f_gen_load (v_Exp62__2)) (I.f_gen_slice (I.f_gen_load (v_result__1)) (I.bigint_of_string "0") (I.bigint_of_string "96")))
    end else begin
      let v_Exp67__2 = I.f_decl_bv ("Exp67__2") (I.bigint_of_string "32") in
      I.f_gen_store (v_Exp67__2) (I.f_gen_FPMulAddH (I.bigint_of_string "32") (I.f_gen_slice (I.f_gen_load (v_Exp18__2)) (I.bigint_of_string "96") (I.bigint_of_string "32")) (I.f_gen_slice (I.f_gen_load (v_Exp12__3)) (I.bigint_of_string "48") (I.bigint_of_string "16")) (I.f_gen_slice (I.f_gen_slice (I.f_gen_lsr_bits (I.bigint_of_string "128") (I.bigint_of_string "16") (I.f_gen_load (v_Exp15__2)) (I.f_gen_bit_lit (I.bigint_of_string "16") (I.f_ZeroExtend (I.bigint_of_string "8") (I.bigint_of_string "16") (I.f_mul_bits (I.bigint_of_string "8") (I.f_ZeroExtend (I.bigint_of_string "3") (I.bigint_of_string "8") (I.f_append_bits (I.bigint_of_string "2") (I.bigint_of_string "1") (I.f_append_bits (I.bigint_of_string "1") (I.bigint_of_string "1") (I.extract_bits (v_enc) (I.bigint_of_string "11") (I.bigint_of_string "1")) (I.extract_bits (v_enc) (I.bigint_of_string "21") (I.bigint_of_string "1"))) (I.extract_bits (v_enc) (I.bigint_of_string "20") (I.bigint_of_string "1"))) (I.bigint_of_string "8")) (I.from_bitsLit "00010000")) (I.bigint_of_string "16")))) (I.bigint_of_string "0") (I.bigint_of_string "16")) (I.bigint_of_string "0") (I.bigint_of_string "16")) (I.f_gen_load (I.v_FPCR)));
      I.f_gen_store (v_result__1) (I.f_gen_append_bits (I.bigint_of_string "32") (I.bigint_of_string "96") (I.f_gen_load (v_Exp67__2)) (I.f_gen_slice (I.f_gen_load (v_result__1)) (I.bigint_of_string "0") (I.bigint_of_string "96")))
    end;
    I.f_gen_array_store (I.v__Z) (I.f_cvt_bits_uint (I.bigint_of_string "5") (I.extract_bits (v_enc) (I.bigint_of_string "0") (I.bigint_of_string "5"))) (I.f_gen_load (v_result__1))
  end else begin
    let v_Exp79__3 = I.f_decl_bv ("Exp79__3") (I.bigint_of_string "128") in
    I.f_gen_store (v_Exp79__3) (I.f_gen_array_load (I.v__Z) (I.f_cvt_bits_uint (I.bigint_of_string "5") (I.extract_bits (v_enc) (I.bigint_of_string "5") (I.bigint_of_string "5"))));
    let v_Exp82__2 = I.f_decl_bv ("Exp82__2") (I.bigint_of_string "128") in
    I.f_gen_store (v_Exp82__2) (I.f_gen_array_load (I.v__Z) (I.f_cvt_bits_uint (I.bigint_of_string "5") (I.f_append_bits (I.bigint_of_string "1") (I.bigint_of_string "4") (I.from_bitsLit "0") (I.extract_bits (v_enc) (I.bigint_of_string "16") (I.bigint_of_string "4")))));
    let v_Exp85__2 = I.f_decl_bv ("Exp85__2") (I.bigint_of_string "128") in
    I.f_gen_store (v_Exp85__2) (I.f_gen_array_load (I.v__Z) (I.f_cvt_bits_uint (I.bigint_of_string "5") (I.extract_bits (v_enc) (I.bigint_of_string "0") (I.bigint_of_string "5"))));
    let v_result__1_1 = I.f_decl_bv ("result__1_1") (I.bigint_of_string "64") in
    if I.f_eq_bits (I.bigint_of_string "32") (I.f_and_bits (I.bigint_of_string "32") (v_enc) (I.from_bitsLit "00000000000000000100000000000000")) (I.from_bitsLit "00000000000000000100000000000000") then begin
      let v_Exp93__2 = I.f_decl_bv ("Exp93__2") (I.bigint_of_string "32") in
      I.f_gen_store (v_Exp93__2) (I.f_gen_FPMulAddH (I.bigint_of_string "32") (I.f_gen_slice (I.f_gen_array_load (I.v__Z) (I.f_cvt_bits_uint (I.bigint_of_string "5") (I.extract_bits (v_enc) (I.bigint_of_string "0") (I.bigint_of_string "5")))) (I.bigint_of_string "0") (I.bigint_of_string "32")) (I.f_gen_append_bits (I.bigint_of_string "1") (I.bigint_of_string "15") (I.f_gen_not_bits (I.bigint_of_string "1") (I.f_gen_slice (I.f_gen_array_load (I.v__Z) (I.f_cvt_bits_uint (I.bigint_of_string "5") (I.extract_bits (v_enc) (I.bigint_of_string "5") (I.bigint_of_string "5")))) (I.bigint_of_string "15") (I.bigint_of_string "1"))) (I.f_gen_slice (I.f_gen_array_load (I.v__Z) (I.f_cvt_bits_uint (I.bigint_of_string "5") (I.extract_bits (v_enc) (I.bigint_of_string "5") (I.bigint_of_string "5")))) (I.bigint_of_string "0") (I.bigint_of_string "15"))) (I.f_gen_slice (I.f_gen_slice (I.f_gen_lsr_bits (I.bigint_of_string "128") (I.bigint_of_string "16") (I.f_gen_array_load (I.v__Z) (I.f_cvt_bits_uint (I.bigint_of_string "5") (I.f_append_bits (I.bigint_of_string "1") (I.bigint_of_string "4") (I.from_bitsLit "0") (I.extract_bits (v_enc) (I.bigint_of_string "16") (I.bigint_of_string "4"))))) (I.f_gen_bit_lit (I.bigint_of_string "16") (I.f_ZeroExtend (I.bigint_of_string "8") (I.bigint_of_string "16") (I.f_mul_bits (I.bigint_of_string "8") (I.f_ZeroExtend (I.bigint_of_string "3") (I.bigint_of_string "8") (I.f_append_bits (I.bigint_of_string "2") (I.bigint_of_string "1") (I.f_append_bits (I.bigint_of_string "1") (I.bigint_of_string "1") (I.extract_bits (v_enc) (I.bigint_of_string "11") (I.bigint_of_string "1")) (I.extract_bits (v_enc) (I.bigint_of_string "21") (I.bigint_of_string "1"))) (I.extract_bits (v_enc) (I.bigint_of_string "20") (I.bigint_of_string "1"))) (I.bigint_of_string "8")) (I.from_bitsLit "00010000")) (I.bigint_of_string "16")))) (I.bigint_of_string "0") (I.bigint_of_string "16")) (I.bigint_of_string "0") (I.bigint_of_string "16")) (I.f_gen_load (I.v_FPCR)));
      I.f_gen_store (v_result__1_1) (I.f_gen_append_bits (I.bigint_of_string "32") (I.bigint_of_string "32") (I.f_gen_slice (I.f_gen_load (v_result__1_1)) (I.bigint_of_string "32") (I.bigint_of_string "32")) (I.f_gen_load (v_Exp93__2)))
    end else begin
      let v_Exp98__2 = I.f_decl_bv ("Exp98__2") (I.bigint_of_string "32") in
      I.f_gen_store (v_Exp98__2) (I.f_gen_FPMulAddH (I.bigint_of_string "32") (I.f_gen_slice (I.f_gen_array_load (I.v__Z) (I.f_cvt_bits_uint (I.bigint_of_string "5") (I.extract_bits (v_enc) (I.bigint_of_string "0") (I.bigint_of_string "5")))) (I.bigint_of_string "0") (I.bigint_of_string "32")) (I.f_gen_slice (I.f_gen_array_load (I.v__Z) (I.f_cvt_bits_uint (I.bigint_of_string "5") (I.extract_bits (v_enc) (I.bigint_of_string "5") (I.bigint_of_string "5")))) (I.bigint_of_string "0") (I.bigint_of_string "16")) (I.f_gen_slice (I.f_gen_slice (I.f_gen_lsr_bits (I.bigint_of_string "128") (I.bigint_of_string "16") (I.f_gen_array_load (I.v__Z) (I.f_cvt_bits_uint (I.bigint_of_string "5") (I.f_append_bits (I.bigint_of_string "1") (I.bigint_of_string "4") (I.from_bitsLit "0") (I.extract_bits (v_enc) (I.bigint_of_string "16") (I.bigint_of_string "4"))))) (I.f_gen_bit_lit (I.bigint_of_string "16") (I.f_ZeroExtend (I.bigint_of_string "8") (I.bigint_of_string "16") (I.f_mul_bits (I.bigint_of_string "8") (I.f_ZeroExtend (I.bigint_of_string "3") (I.bigint_of_string "8") (I.f_append_bits (I.bigint_of_string "2") (I.bigint_of_string "1") (I.f_append_bits (I.bigint_of_string "1") (I.bigint_of_string "1") (I.extract_bits (v_enc) (I.bigint_of_string "11") (I.bigint_of_string "1")) (I.extract_bits (v_enc) (I.bigint_of_string "21") (I.bigint_of_string "1"))) (I.extract_bits (v_enc) (I.bigint_of_string "20") (I.bigint_of_string "1"))) (I.bigint_of_string "8")) (I.from_bitsLit "00010000")) (I.bigint_of_string "16")))) (I.bigint_of_string "0") (I.bigint_of_string "16")) (I.bigint_of_string "0") (I.bigint_of_string "16")) (I.f_gen_load (I.v_FPCR)));
      I.f_gen_store (v_result__1_1) (I.f_gen_append_bits (I.bigint_of_string "32") (I.bigint_of_string "32") (I.f_gen_slice (I.f_gen_load (v_result__1_1)) (I.bigint_of_string "32") (I.bigint_of_string "32")) (I.f_gen_load (v_Exp98__2)))
    end;
    if I.f_eq_bits (I.bigint_of_string "32") (I.f_and_bits (I.bigint_of_string "32") (v_enc) (I.from_bitsLit "00000000000000000100000000000000")) (I.from_bitsLit "00000000000000000100000000000000") then begin
      let v_Exp105__2 = I.f_decl_bv ("Exp105__2") (I.bigint_of_string "32") in
      I.f_gen_store (v_Exp105__2) (I.f_gen_FPMulAddH (I.bigint_of_string "32") (I.f_gen_slice (I.f_gen_load (v_Exp85__2)) (I.bigint_of_string "32") (I.bigint_of_string "32")) (I.f_gen_append_bits (I.bigint_of_string "1") (I.bigint_of_string "15") (I.f_gen_not_bits (I.bigint_of_string "1") (I.f_gen_slice (I.f_gen_load (v_Exp79__3)) (I.bigint_of_string "31") (I.bigint_of_string "1"))) (I.f_gen_slice (I.f_gen_load (v_Exp79__3)) (I.bigint_of_string "16") (I.bigint_of_string "15"))) (I.f_gen_slice (I.f_gen_slice (I.f_gen_lsr_bits (I.bigint_of_string "128") (I.bigint_of_string "16") (I.f_gen_load (v_Exp82__2)) (I.f_gen_bit_lit (I.bigint_of_string "16") (I.f_ZeroExtend (I.bigint_of_string "8") (I.bigint_of_string "16") (I.f_mul_bits (I.bigint_of_string "8") (I.f_ZeroExtend (I.bigint_of_string "3") (I.bigint_of_string "8") (I.f_append_bits (I.bigint_of_string "2") (I.bigint_of_string "1") (I.f_append_bits (I.bigint_of_string "1") (I.bigint_of_string "1") (I.extract_bits (v_enc) (I.bigint_of_string "11") (I.bigint_of_string "1")) (I.extract_bits (v_enc) (I.bigint_of_string "21") (I.bigint_of_string "1"))) (I.extract_bits (v_enc) (I.bigint_of_string "20") (I.bigint_of_string "1"))) (I.bigint_of_string "8")) (I.from_bitsLit "00010000")) (I.bigint_of_string "16")))) (I.bigint_of_string "0") (I.bigint_of_string "16")) (I.bigint_of_string "0") (I.bigint_of_string "16")) (I.f_gen_load (I.v_FPCR)));
      I.f_gen_store (v_result__1_1) (I.f_gen_append_bits (I.bigint_of_string "32") (I.bigint_of_string "32") (I.f_gen_load (v_Exp105__2)) (I.f_gen_slice (I.f_gen_load (v_result__1_1)) (I.bigint_of_string "0") (I.bigint_of_string "32")))
    end else begin
      let v_Exp110__2 = I.f_decl_bv ("Exp110__2") (I.bigint_of_string "32") in
      I.f_gen_store (v_Exp110__2) (I.f_gen_FPMulAddH (I.bigint_of_string "32") (I.f_gen_slice (I.f_gen_load (v_Exp85__2)) (I.bigint_of_string "32") (I.bigint_of_string "32")) (I.f_gen_slice (I.f_gen_load (v_Exp79__3)) (I.bigint_of_string "16") (I.bigint_of_string "16")) (I.f_gen_slice (I.f_gen_slice (I.f_gen_lsr_bits (I.bigint_of_string "128") (I.bigint_of_string "16") (I.f_gen_load (v_Exp82__2)) (I.f_gen_bit_lit (I.bigint_of_string "16") (I.f_ZeroExtend (I.bigint_of_string "8") (I.bigint_of_string "16") (I.f_mul_bits (I.bigint_of_string "8") (I.f_ZeroExtend (I.bigint_of_string "3") (I.bigint_of_string "8") (I.f_append_bits (I.bigint_of_string "2") (I.bigint_of_string "1") (I.f_append_bits (I.bigint_of_string "1") (I.bigint_of_string "1") (I.extract_bits (v_enc) (I.bigint_of_string "11") (I.bigint_of_string "1")) (I.extract_bits (v_enc) (I.bigint_of_string "21") (I.bigint_of_string "1"))) (I.extract_bits (v_enc) (I.bigint_of_string "20") (I.bigint_of_string "1"))) (I.bigint_of_string "8")) (I.from_bitsLit "00010000")) (I.bigint_of_string "16")))) (I.bigint_of_string "0") (I.bigint_of_string "16")) (I.bigint_of_string "0") (I.bigint_of_string "16")) (I.f_gen_load (I.v_FPCR)));
      I.f_gen_store (v_result__1_1) (I.f_gen_append_bits (I.bigint_of_string "32") (I.bigint_of_string "32") (I.f_gen_load (v_Exp110__2)) (I.f_gen_slice (I.f_gen_load (v_result__1_1)) (I.bigint_of_string "0") (I.bigint_of_string "32")))
    end;
    I.f_gen_array_store (I.v__Z) (I.f_cvt_bits_uint (I.bigint_of_string "5") (I.extract_bits (v_enc) (I.bigint_of_string "0") (I.bigint_of_string "5"))) (I.f_gen_ZeroExtend (I.bigint_of_string "64") (I.bigint_of_string "128") (I.f_gen_load (v_result__1_1)) (I.f_gen_int_lit (I.bigint_of_string "128")))
  end

