(* AUTO-GENERATED LIFTER FILE *)

open Instruction_building_interface

let f_aarch64_vector_fp16_movi (type bitvector) (module I : IBI with type bitvector = bitvector) (v_enc : bitvector) (v_pc : bitvector) : unit = 
  if I.f_eq_bits (I.bigint_of_string "32") (I.f_and_bits (I.bigint_of_string "32") (v_enc) (I.from_bitsLit "01000000000000000000000000000000")) (I.from_bitsLit "01000000000000000000000000000000") then begin
    I.f_gen_array_store (I.v__Z) (I.f_cvt_bits_uint (I.bigint_of_string "5") (I.extract_bits (v_enc) (I.bigint_of_string "0") (I.bigint_of_string "5"))) (I.f_gen_bit_lit (I.bigint_mul (I.bigint_of_string "16") (I.bigint_of_string "8")) (I.f_replicate_bits (I.bigint_of_string "16") (I.bigint_of_string "8") (I.f_append_bits (I.bigint_of_string "10") (I.bigint_of_string "6") (I.f_append_bits (I.bigint_of_string "4") (I.bigint_of_string "6") (I.f_append_bits (I.bigint_of_string "2") (I.bigint_of_string "2") (I.f_append_bits (I.bigint_of_string "1") (I.bigint_of_string "1") (I.extract_bits (v_enc) (I.bigint_of_string "18") (I.bigint_of_string "1")) (I.f_not_bits (I.bigint_of_string "1") (I.extract_bits (v_enc) (I.bigint_of_string "17") (I.bigint_of_string "1")))) (I.f_replicate_bits (I.bigint_of_string "1") (I.bigint_of_string "2") (I.extract_bits (v_enc) (I.bigint_of_string "17") (I.bigint_of_string "1")) (I.bigint_of_string "2"))) (I.f_append_bits (I.bigint_of_string "5") (I.bigint_of_string "1") (I.f_append_bits (I.bigint_of_string "4") (I.bigint_of_string "1") (I.f_append_bits (I.bigint_of_string "3") (I.bigint_of_string "1") (I.f_append_bits (I.bigint_of_string "2") (I.bigint_of_string "1") (I.f_append_bits (I.bigint_of_string "1") (I.bigint_of_string "1") (I.extract_bits (v_enc) (I.bigint_of_string "16") (I.bigint_of_string "1")) (I.extract_bits (v_enc) (I.bigint_of_string "9") (I.bigint_of_string "1"))) (I.extract_bits (v_enc) (I.bigint_of_string "8") (I.bigint_of_string "1"))) (I.extract_bits (v_enc) (I.bigint_of_string "7") (I.bigint_of_string "1"))) (I.extract_bits (v_enc) (I.bigint_of_string "6") (I.bigint_of_string "1"))) (I.extract_bits (v_enc) (I.bigint_of_string "5") (I.bigint_of_string "1")))) (I.from_bitsLit "000000")) (I.bigint_of_string "8")))
  end else begin
    I.f_gen_array_store (I.v__Z) (I.f_cvt_bits_uint (I.bigint_of_string "5") (I.extract_bits (v_enc) (I.bigint_of_string "0") (I.bigint_of_string "5"))) (I.f_gen_bit_lit (I.bigint_of_string "128") (I.f_ZeroExtend (I.bigint_of_string "64") (I.bigint_of_string "128") (I.f_replicate_bits (I.bigint_of_string "16") (I.bigint_of_string "4") (I.f_append_bits (I.bigint_of_string "10") (I.bigint_of_string "6") (I.f_append_bits (I.bigint_of_string "4") (I.bigint_of_string "6") (I.f_append_bits (I.bigint_of_string "2") (I.bigint_of_string "2") (I.f_append_bits (I.bigint_of_string "1") (I.bigint_of_string "1") (I.extract_bits (v_enc) (I.bigint_of_string "18") (I.bigint_of_string "1")) (I.f_not_bits (I.bigint_of_string "1") (I.extract_bits (v_enc) (I.bigint_of_string "17") (I.bigint_of_string "1")))) (I.f_replicate_bits (I.bigint_of_string "1") (I.bigint_of_string "2") (I.extract_bits (v_enc) (I.bigint_of_string "17") (I.bigint_of_string "1")) (I.bigint_of_string "2"))) (I.f_append_bits (I.bigint_of_string "5") (I.bigint_of_string "1") (I.f_append_bits (I.bigint_of_string "4") (I.bigint_of_string "1") (I.f_append_bits (I.bigint_of_string "3") (I.bigint_of_string "1") (I.f_append_bits (I.bigint_of_string "2") (I.bigint_of_string "1") (I.f_append_bits (I.bigint_of_string "1") (I.bigint_of_string "1") (I.extract_bits (v_enc) (I.bigint_of_string "16") (I.bigint_of_string "1")) (I.extract_bits (v_enc) (I.bigint_of_string "9") (I.bigint_of_string "1"))) (I.extract_bits (v_enc) (I.bigint_of_string "8") (I.bigint_of_string "1"))) (I.extract_bits (v_enc) (I.bigint_of_string "7") (I.bigint_of_string "1"))) (I.extract_bits (v_enc) (I.bigint_of_string "6") (I.bigint_of_string "1"))) (I.extract_bits (v_enc) (I.bigint_of_string "5") (I.bigint_of_string "1")))) (I.from_bitsLit "000000")) (I.bigint_of_string "4")) (I.bigint_of_string "128")))
  end

