(* AUTO-GENERATED LIFTER FILE *)

open Instruction_building_interface

let f_aarch64_vector_logical (type bitvector) (module I : IBI with type bitvector = bitvector) (v_enc : bitvector) : unit = 
  if I.f_eq_bits (I.bigint_of_string "32") (I.f_and_bits (I.bigint_of_string "32") (v_enc) (I.from_bitsLit "01000000000000000000000000000000")) (I.from_bitsLit "01000000000000000000000000000000") then begin
    let v_imm64__2 = ref (I.mkBits (I.bigint_of_string "64") I.bigint_zero) in
    if I.f_eq_bits (I.bigint_of_string "32") (I.f_and_bits (I.bigint_of_string "32") (v_enc) (I.from_bitsLit "00000000000000001110000000000000")) (I.from_bitsLit "00000000000000000000000000000000") then begin
      v_imm64__2 := I.f_replicate_bits (I.bigint_of_string "32") (I.bigint_of_string "2") (I.f_append_bits (I.bigint_of_string "24") (I.bigint_of_string "8") (I.from_bitsLit "000000000000000000000000") (I.f_append_bits (I.bigint_of_string "7") (I.bigint_of_string "1") (I.f_append_bits (I.bigint_of_string "6") (I.bigint_of_string "1") (I.f_append_bits (I.bigint_of_string "5") (I.bigint_of_string "1") (I.f_append_bits (I.bigint_of_string "4") (I.bigint_of_string "1") (I.f_append_bits (I.bigint_of_string "3") (I.bigint_of_string "1") (I.f_append_bits (I.bigint_of_string "2") (I.bigint_of_string "1") (I.f_append_bits (I.bigint_of_string "1") (I.bigint_of_string "1") (I.extract_bits (v_enc) (I.bigint_of_string "18") (I.bigint_of_string "1")) (I.extract_bits (v_enc) (I.bigint_of_string "17") (I.bigint_of_string "1"))) (I.extract_bits (v_enc) (I.bigint_of_string "16") (I.bigint_of_string "1"))) (I.extract_bits (v_enc) (I.bigint_of_string "9") (I.bigint_of_string "1"))) (I.extract_bits (v_enc) (I.bigint_of_string "8") (I.bigint_of_string "1"))) (I.extract_bits (v_enc) (I.bigint_of_string "7") (I.bigint_of_string "1"))) (I.extract_bits (v_enc) (I.bigint_of_string "6") (I.bigint_of_string "1"))) (I.extract_bits (v_enc) (I.bigint_of_string "5") (I.bigint_of_string "1")))) (I.bigint_of_string "2")
    end else begin
      if I.f_eq_bits (I.bigint_of_string "32") (I.f_and_bits (I.bigint_of_string "32") (v_enc) (I.from_bitsLit "00000000000000001110000000000000")) (I.from_bitsLit "00000000000000000010000000000000") then begin
        v_imm64__2 := I.f_replicate_bits (I.bigint_of_string "32") (I.bigint_of_string "2") (I.f_append_bits (I.bigint_of_string "24") (I.bigint_of_string "8") (I.f_append_bits (I.bigint_of_string "16") (I.bigint_of_string "8") (I.from_bitsLit "0000000000000000") (I.f_append_bits (I.bigint_of_string "7") (I.bigint_of_string "1") (I.f_append_bits (I.bigint_of_string "6") (I.bigint_of_string "1") (I.f_append_bits (I.bigint_of_string "5") (I.bigint_of_string "1") (I.f_append_bits (I.bigint_of_string "4") (I.bigint_of_string "1") (I.f_append_bits (I.bigint_of_string "3") (I.bigint_of_string "1") (I.f_append_bits (I.bigint_of_string "2") (I.bigint_of_string "1") (I.f_append_bits (I.bigint_of_string "1") (I.bigint_of_string "1") (I.extract_bits (v_enc) (I.bigint_of_string "18") (I.bigint_of_string "1")) (I.extract_bits (v_enc) (I.bigint_of_string "17") (I.bigint_of_string "1"))) (I.extract_bits (v_enc) (I.bigint_of_string "16") (I.bigint_of_string "1"))) (I.extract_bits (v_enc) (I.bigint_of_string "9") (I.bigint_of_string "1"))) (I.extract_bits (v_enc) (I.bigint_of_string "8") (I.bigint_of_string "1"))) (I.extract_bits (v_enc) (I.bigint_of_string "7") (I.bigint_of_string "1"))) (I.extract_bits (v_enc) (I.bigint_of_string "6") (I.bigint_of_string "1"))) (I.extract_bits (v_enc) (I.bigint_of_string "5") (I.bigint_of_string "1")))) (I.from_bitsLit "00000000")) (I.bigint_of_string "2")
      end else begin
        if I.f_eq_bits (I.bigint_of_string "32") (I.f_and_bits (I.bigint_of_string "32") (v_enc) (I.from_bitsLit "00000000000000001110000000000000")) (I.from_bitsLit "00000000000000000100000000000000") then begin
          v_imm64__2 := I.f_replicate_bits (I.bigint_of_string "32") (I.bigint_of_string "2") (I.f_append_bits (I.bigint_of_string "16") (I.bigint_of_string "16") (I.f_append_bits (I.bigint_of_string "8") (I.bigint_of_string "8") (I.from_bitsLit "00000000") (I.f_append_bits (I.bigint_of_string "7") (I.bigint_of_string "1") (I.f_append_bits (I.bigint_of_string "6") (I.bigint_of_string "1") (I.f_append_bits (I.bigint_of_string "5") (I.bigint_of_string "1") (I.f_append_bits (I.bigint_of_string "4") (I.bigint_of_string "1") (I.f_append_bits (I.bigint_of_string "3") (I.bigint_of_string "1") (I.f_append_bits (I.bigint_of_string "2") (I.bigint_of_string "1") (I.f_append_bits (I.bigint_of_string "1") (I.bigint_of_string "1") (I.extract_bits (v_enc) (I.bigint_of_string "18") (I.bigint_of_string "1")) (I.extract_bits (v_enc) (I.bigint_of_string "17") (I.bigint_of_string "1"))) (I.extract_bits (v_enc) (I.bigint_of_string "16") (I.bigint_of_string "1"))) (I.extract_bits (v_enc) (I.bigint_of_string "9") (I.bigint_of_string "1"))) (I.extract_bits (v_enc) (I.bigint_of_string "8") (I.bigint_of_string "1"))) (I.extract_bits (v_enc) (I.bigint_of_string "7") (I.bigint_of_string "1"))) (I.extract_bits (v_enc) (I.bigint_of_string "6") (I.bigint_of_string "1"))) (I.extract_bits (v_enc) (I.bigint_of_string "5") (I.bigint_of_string "1")))) (I.from_bitsLit "0000000000000000")) (I.bigint_of_string "2")
        end else begin
          if I.f_eq_bits (I.bigint_of_string "32") (I.f_and_bits (I.bigint_of_string "32") (v_enc) (I.from_bitsLit "00000000000000001110000000000000")) (I.from_bitsLit "00000000000000000110000000000000") then begin
            v_imm64__2 := I.f_replicate_bits (I.bigint_of_string "32") (I.bigint_of_string "2") (I.f_append_bits (I.bigint_of_string "8") (I.bigint_of_string "24") (I.f_append_bits (I.bigint_of_string "7") (I.bigint_of_string "1") (I.f_append_bits (I.bigint_of_string "6") (I.bigint_of_string "1") (I.f_append_bits (I.bigint_of_string "5") (I.bigint_of_string "1") (I.f_append_bits (I.bigint_of_string "4") (I.bigint_of_string "1") (I.f_append_bits (I.bigint_of_string "3") (I.bigint_of_string "1") (I.f_append_bits (I.bigint_of_string "2") (I.bigint_of_string "1") (I.f_append_bits (I.bigint_of_string "1") (I.bigint_of_string "1") (I.extract_bits (v_enc) (I.bigint_of_string "18") (I.bigint_of_string "1")) (I.extract_bits (v_enc) (I.bigint_of_string "17") (I.bigint_of_string "1"))) (I.extract_bits (v_enc) (I.bigint_of_string "16") (I.bigint_of_string "1"))) (I.extract_bits (v_enc) (I.bigint_of_string "9") (I.bigint_of_string "1"))) (I.extract_bits (v_enc) (I.bigint_of_string "8") (I.bigint_of_string "1"))) (I.extract_bits (v_enc) (I.bigint_of_string "7") (I.bigint_of_string "1"))) (I.extract_bits (v_enc) (I.bigint_of_string "6") (I.bigint_of_string "1"))) (I.extract_bits (v_enc) (I.bigint_of_string "5") (I.bigint_of_string "1"))) (I.from_bitsLit "000000000000000000000000")) (I.bigint_of_string "2")
          end else begin
            if I.f_eq_bits (I.bigint_of_string "32") (I.f_and_bits (I.bigint_of_string "32") (v_enc) (I.from_bitsLit "00000000000000001110000000000000")) (I.from_bitsLit "00000000000000001000000000000000") then begin
              v_imm64__2 := I.f_replicate_bits (I.bigint_of_string "16") (I.bigint_of_string "4") (I.f_append_bits (I.bigint_of_string "8") (I.bigint_of_string "8") (I.from_bitsLit "00000000") (I.f_append_bits (I.bigint_of_string "7") (I.bigint_of_string "1") (I.f_append_bits (I.bigint_of_string "6") (I.bigint_of_string "1") (I.f_append_bits (I.bigint_of_string "5") (I.bigint_of_string "1") (I.f_append_bits (I.bigint_of_string "4") (I.bigint_of_string "1") (I.f_append_bits (I.bigint_of_string "3") (I.bigint_of_string "1") (I.f_append_bits (I.bigint_of_string "2") (I.bigint_of_string "1") (I.f_append_bits (I.bigint_of_string "1") (I.bigint_of_string "1") (I.extract_bits (v_enc) (I.bigint_of_string "18") (I.bigint_of_string "1")) (I.extract_bits (v_enc) (I.bigint_of_string "17") (I.bigint_of_string "1"))) (I.extract_bits (v_enc) (I.bigint_of_string "16") (I.bigint_of_string "1"))) (I.extract_bits (v_enc) (I.bigint_of_string "9") (I.bigint_of_string "1"))) (I.extract_bits (v_enc) (I.bigint_of_string "8") (I.bigint_of_string "1"))) (I.extract_bits (v_enc) (I.bigint_of_string "7") (I.bigint_of_string "1"))) (I.extract_bits (v_enc) (I.bigint_of_string "6") (I.bigint_of_string "1"))) (I.extract_bits (v_enc) (I.bigint_of_string "5") (I.bigint_of_string "1")))) (I.bigint_of_string "4")
            end else begin
              if I.f_eq_bits (I.bigint_of_string "32") (I.f_and_bits (I.bigint_of_string "32") (v_enc) (I.from_bitsLit "00000000000000001110000000000000")) (I.from_bitsLit "00000000000000001010000000000000") then begin
                v_imm64__2 := I.f_replicate_bits (I.bigint_of_string "16") (I.bigint_of_string "4") (I.f_append_bits (I.bigint_of_string "8") (I.bigint_of_string "8") (I.f_append_bits (I.bigint_of_string "7") (I.bigint_of_string "1") (I.f_append_bits (I.bigint_of_string "6") (I.bigint_of_string "1") (I.f_append_bits (I.bigint_of_string "5") (I.bigint_of_string "1") (I.f_append_bits (I.bigint_of_string "4") (I.bigint_of_string "1") (I.f_append_bits (I.bigint_of_string "3") (I.bigint_of_string "1") (I.f_append_bits (I.bigint_of_string "2") (I.bigint_of_string "1") (I.f_append_bits (I.bigint_of_string "1") (I.bigint_of_string "1") (I.extract_bits (v_enc) (I.bigint_of_string "18") (I.bigint_of_string "1")) (I.extract_bits (v_enc) (I.bigint_of_string "17") (I.bigint_of_string "1"))) (I.extract_bits (v_enc) (I.bigint_of_string "16") (I.bigint_of_string "1"))) (I.extract_bits (v_enc) (I.bigint_of_string "9") (I.bigint_of_string "1"))) (I.extract_bits (v_enc) (I.bigint_of_string "8") (I.bigint_of_string "1"))) (I.extract_bits (v_enc) (I.bigint_of_string "7") (I.bigint_of_string "1"))) (I.extract_bits (v_enc) (I.bigint_of_string "6") (I.bigint_of_string "1"))) (I.extract_bits (v_enc) (I.bigint_of_string "5") (I.bigint_of_string "1"))) (I.from_bitsLit "00000000")) (I.bigint_of_string "4")
              end else begin
                if I.f_eq_bits (I.bigint_of_string "32") (I.f_and_bits (I.bigint_of_string "32") (v_enc) (I.from_bitsLit "00000000000000001110000000000000")) (I.from_bitsLit "00000000000000001100000000000000") then begin
                  if I.f_eq_bits (I.bigint_of_string "32") (I.f_and_bits (I.bigint_of_string "32") (v_enc) (I.from_bitsLit "00000000000000000001000000000000")) (I.from_bitsLit "00000000000000000000000000000000") then begin
                    v_imm64__2 := I.f_replicate_bits (I.bigint_of_string "32") (I.bigint_of_string "2") (I.f_append_bits (I.bigint_of_string "24") (I.bigint_of_string "8") (I.f_append_bits (I.bigint_of_string "16") (I.bigint_of_string "8") (I.from_bitsLit "0000000000000000") (I.f_append_bits (I.bigint_of_string "7") (I.bigint_of_string "1") (I.f_append_bits (I.bigint_of_string "6") (I.bigint_of_string "1") (I.f_append_bits (I.bigint_of_string "5") (I.bigint_of_string "1") (I.f_append_bits (I.bigint_of_string "4") (I.bigint_of_string "1") (I.f_append_bits (I.bigint_of_string "3") (I.bigint_of_string "1") (I.f_append_bits (I.bigint_of_string "2") (I.bigint_of_string "1") (I.f_append_bits (I.bigint_of_string "1") (I.bigint_of_string "1") (I.extract_bits (v_enc) (I.bigint_of_string "18") (I.bigint_of_string "1")) (I.extract_bits (v_enc) (I.bigint_of_string "17") (I.bigint_of_string "1"))) (I.extract_bits (v_enc) (I.bigint_of_string "16") (I.bigint_of_string "1"))) (I.extract_bits (v_enc) (I.bigint_of_string "9") (I.bigint_of_string "1"))) (I.extract_bits (v_enc) (I.bigint_of_string "8") (I.bigint_of_string "1"))) (I.extract_bits (v_enc) (I.bigint_of_string "7") (I.bigint_of_string "1"))) (I.extract_bits (v_enc) (I.bigint_of_string "6") (I.bigint_of_string "1"))) (I.extract_bits (v_enc) (I.bigint_of_string "5") (I.bigint_of_string "1")))) (I.from_bitsLit "11111111")) (I.bigint_of_string "2")
                  end else begin
                    v_imm64__2 := I.f_replicate_bits (I.bigint_of_string "32") (I.bigint_of_string "2") (I.f_append_bits (I.bigint_of_string "16") (I.bigint_of_string "16") (I.f_append_bits (I.bigint_of_string "8") (I.bigint_of_string "8") (I.from_bitsLit "00000000") (I.f_append_bits (I.bigint_of_string "7") (I.bigint_of_string "1") (I.f_append_bits (I.bigint_of_string "6") (I.bigint_of_string "1") (I.f_append_bits (I.bigint_of_string "5") (I.bigint_of_string "1") (I.f_append_bits (I.bigint_of_string "4") (I.bigint_of_string "1") (I.f_append_bits (I.bigint_of_string "3") (I.bigint_of_string "1") (I.f_append_bits (I.bigint_of_string "2") (I.bigint_of_string "1") (I.f_append_bits (I.bigint_of_string "1") (I.bigint_of_string "1") (I.extract_bits (v_enc) (I.bigint_of_string "18") (I.bigint_of_string "1")) (I.extract_bits (v_enc) (I.bigint_of_string "17") (I.bigint_of_string "1"))) (I.extract_bits (v_enc) (I.bigint_of_string "16") (I.bigint_of_string "1"))) (I.extract_bits (v_enc) (I.bigint_of_string "9") (I.bigint_of_string "1"))) (I.extract_bits (v_enc) (I.bigint_of_string "8") (I.bigint_of_string "1"))) (I.extract_bits (v_enc) (I.bigint_of_string "7") (I.bigint_of_string "1"))) (I.extract_bits (v_enc) (I.bigint_of_string "6") (I.bigint_of_string "1"))) (I.extract_bits (v_enc) (I.bigint_of_string "5") (I.bigint_of_string "1")))) (I.from_bitsLit "1111111111111111")) (I.bigint_of_string "2")
                  end
                end else begin
                  if I.f_eq_bits (I.bigint_of_string "32") (I.f_and_bits (I.bigint_of_string "32") (v_enc) (I.from_bitsLit "00100000000000000001000000000000")) (I.from_bitsLit "00000000000000000000000000000000") then begin
                    v_imm64__2 := I.f_replicate_bits (I.bigint_of_string "8") (I.bigint_of_string "8") (I.f_append_bits (I.bigint_of_string "7") (I.bigint_of_string "1") (I.f_append_bits (I.bigint_of_string "6") (I.bigint_of_string "1") (I.f_append_bits (I.bigint_of_string "5") (I.bigint_of_string "1") (I.f_append_bits (I.bigint_of_string "4") (I.bigint_of_string "1") (I.f_append_bits (I.bigint_of_string "3") (I.bigint_of_string "1") (I.f_append_bits (I.bigint_of_string "2") (I.bigint_of_string "1") (I.f_append_bits (I.bigint_of_string "1") (I.bigint_of_string "1") (I.extract_bits (v_enc) (I.bigint_of_string "18") (I.bigint_of_string "1")) (I.extract_bits (v_enc) (I.bigint_of_string "17") (I.bigint_of_string "1"))) (I.extract_bits (v_enc) (I.bigint_of_string "16") (I.bigint_of_string "1"))) (I.extract_bits (v_enc) (I.bigint_of_string "9") (I.bigint_of_string "1"))) (I.extract_bits (v_enc) (I.bigint_of_string "8") (I.bigint_of_string "1"))) (I.extract_bits (v_enc) (I.bigint_of_string "7") (I.bigint_of_string "1"))) (I.extract_bits (v_enc) (I.bigint_of_string "6") (I.bigint_of_string "1"))) (I.extract_bits (v_enc) (I.bigint_of_string "5") (I.bigint_of_string "1"))) (I.bigint_of_string "8")
                  end else begin
                    if I.f_eq_bits (I.bigint_of_string "32") (I.f_and_bits (I.bigint_of_string "32") (v_enc) (I.from_bitsLit "00100000000000000001000000000000")) (I.from_bitsLit "00100000000000000000000000000000") then begin
                      v_imm64__2 := I.f_append_bits (I.bigint_of_string "56") (I.bigint_of_string "8") (I.f_append_bits (I.bigint_of_string "48") (I.bigint_of_string "8") (I.f_append_bits (I.bigint_of_string "40") (I.bigint_of_string "8") (I.f_append_bits (I.bigint_of_string "32") (I.bigint_of_string "8") (I.f_append_bits (I.bigint_of_string "24") (I.bigint_of_string "8") (I.f_append_bits (I.bigint_of_string "16") (I.bigint_of_string "8") (I.f_append_bits (I.bigint_of_string "8") (I.bigint_of_string "8") (I.f_replicate_bits (I.bigint_of_string "1") (I.bigint_of_string "8") (I.extract_bits (v_enc) (I.bigint_of_string "18") (I.bigint_of_string "1")) (I.bigint_of_string "8")) (I.f_replicate_bits (I.bigint_of_string "1") (I.bigint_of_string "8") (I.extract_bits (v_enc) (I.bigint_of_string "17") (I.bigint_of_string "1")) (I.bigint_of_string "8"))) (I.f_replicate_bits (I.bigint_of_string "1") (I.bigint_of_string "8") (I.extract_bits (v_enc) (I.bigint_of_string "16") (I.bigint_of_string "1")) (I.bigint_of_string "8"))) (I.f_replicate_bits (I.bigint_of_string "1") (I.bigint_of_string "8") (I.extract_bits (v_enc) (I.bigint_of_string "9") (I.bigint_of_string "1")) (I.bigint_of_string "8"))) (I.f_replicate_bits (I.bigint_of_string "1") (I.bigint_of_string "8") (I.extract_bits (v_enc) (I.bigint_of_string "8") (I.bigint_of_string "1")) (I.bigint_of_string "8"))) (I.f_replicate_bits (I.bigint_of_string "1") (I.bigint_of_string "8") (I.extract_bits (v_enc) (I.bigint_of_string "7") (I.bigint_of_string "1")) (I.bigint_of_string "8"))) (I.f_replicate_bits (I.bigint_of_string "1") (I.bigint_of_string "8") (I.extract_bits (v_enc) (I.bigint_of_string "6") (I.bigint_of_string "1")) (I.bigint_of_string "8"))) (I.f_replicate_bits (I.bigint_of_string "1") (I.bigint_of_string "8") (I.extract_bits (v_enc) (I.bigint_of_string "5") (I.bigint_of_string "1")) (I.bigint_of_string "8"))
                    end else begin
                      if I.f_eq_bits (I.bigint_of_string "32") (I.f_and_bits (I.bigint_of_string "32") (v_enc) (I.from_bitsLit "00100000000000000001000000000000")) (I.from_bitsLit "00000000000000000001000000000000") then begin
                        v_imm64__2 := I.f_replicate_bits (I.bigint_of_string "32") (I.bigint_of_string "2") (I.f_append_bits (I.bigint_of_string "13") (I.bigint_of_string "19") (I.f_append_bits (I.bigint_of_string "7") (I.bigint_of_string "6") (I.f_append_bits (I.bigint_of_string "2") (I.bigint_of_string "5") (I.f_append_bits (I.bigint_of_string "1") (I.bigint_of_string "1") (I.extract_bits (v_enc) (I.bigint_of_string "18") (I.bigint_of_string "1")) (I.f_not_bits (I.bigint_of_string "1") (I.extract_bits (v_enc) (I.bigint_of_string "17") (I.bigint_of_string "1")))) (I.f_replicate_bits (I.bigint_of_string "1") (I.bigint_of_string "5") (I.extract_bits (v_enc) (I.bigint_of_string "17") (I.bigint_of_string "1")) (I.bigint_of_string "5"))) (I.f_append_bits (I.bigint_of_string "5") (I.bigint_of_string "1") (I.f_append_bits (I.bigint_of_string "4") (I.bigint_of_string "1") (I.f_append_bits (I.bigint_of_string "3") (I.bigint_of_string "1") (I.f_append_bits (I.bigint_of_string "2") (I.bigint_of_string "1") (I.f_append_bits (I.bigint_of_string "1") (I.bigint_of_string "1") (I.extract_bits (v_enc) (I.bigint_of_string "16") (I.bigint_of_string "1")) (I.extract_bits (v_enc) (I.bigint_of_string "9") (I.bigint_of_string "1"))) (I.extract_bits (v_enc) (I.bigint_of_string "8") (I.bigint_of_string "1"))) (I.extract_bits (v_enc) (I.bigint_of_string "7") (I.bigint_of_string "1"))) (I.extract_bits (v_enc) (I.bigint_of_string "6") (I.bigint_of_string "1"))) (I.extract_bits (v_enc) (I.bigint_of_string "5") (I.bigint_of_string "1")))) (I.from_bitsLit "0000000000000000000")) (I.bigint_of_string "2")
                      end else begin
                        v_imm64__2 := I.f_append_bits (I.bigint_of_string "16") (I.bigint_of_string "48") (I.f_append_bits (I.bigint_of_string "10") (I.bigint_of_string "6") (I.f_append_bits (I.bigint_of_string "2") (I.bigint_of_string "8") (I.f_append_bits (I.bigint_of_string "1") (I.bigint_of_string "1") (I.extract_bits (v_enc) (I.bigint_of_string "18") (I.bigint_of_string "1")) (I.f_not_bits (I.bigint_of_string "1") (I.extract_bits (v_enc) (I.bigint_of_string "17") (I.bigint_of_string "1")))) (I.f_replicate_bits (I.bigint_of_string "1") (I.bigint_of_string "8") (I.extract_bits (v_enc) (I.bigint_of_string "17") (I.bigint_of_string "1")) (I.bigint_of_string "8"))) (I.f_append_bits (I.bigint_of_string "5") (I.bigint_of_string "1") (I.f_append_bits (I.bigint_of_string "4") (I.bigint_of_string "1") (I.f_append_bits (I.bigint_of_string "3") (I.bigint_of_string "1") (I.f_append_bits (I.bigint_of_string "2") (I.bigint_of_string "1") (I.f_append_bits (I.bigint_of_string "1") (I.bigint_of_string "1") (I.extract_bits (v_enc) (I.bigint_of_string "16") (I.bigint_of_string "1")) (I.extract_bits (v_enc) (I.bigint_of_string "9") (I.bigint_of_string "1"))) (I.extract_bits (v_enc) (I.bigint_of_string "8") (I.bigint_of_string "1"))) (I.extract_bits (v_enc) (I.bigint_of_string "7") (I.bigint_of_string "1"))) (I.extract_bits (v_enc) (I.bigint_of_string "6") (I.bigint_of_string "1"))) (I.extract_bits (v_enc) (I.bigint_of_string "5") (I.bigint_of_string "1")))) (I.from_bitsLit "000000000000000000000000000000000000000000000000")
                      end
                    end
                  end
                end
              end
            end
          end
        end
      end
    end;
    let v_result__1 = I.f_decl_bv ("result__1") (I.bigint_of_string "128") in
    if ((I.f_eq_bits (I.bigint_of_string "32") (I.f_and_bits (I.bigint_of_string "32") (v_enc) (I.from_bitsLit "00100000000000001100000000000000")) (I.from_bitsLit "00000000000000001100000000000000")) || (I.f_eq_bits (I.bigint_of_string "32") (I.f_and_bits (I.bigint_of_string "32") (v_enc) (I.from_bitsLit "00000000000000001110000000000000")) (I.from_bitsLit "00000000000000001110000000000000"))) || (I.f_eq_bits (I.bigint_of_string "32") (I.f_and_bits (I.bigint_of_string "32") (v_enc) (I.from_bitsLit "00100000000000000001000000000000")) (I.from_bitsLit "00000000000000000000000000000000")) then begin
      I.f_gen_store (v_result__1) (I.f_gen_bit_lit (I.bigint_mul (I.bigint_of_string "64") (I.bigint_of_string "2")) (I.f_replicate_bits (I.bigint_of_string "64") (I.bigint_of_string "2") (!v_imm64__2) (I.bigint_of_string "2")))
    end else begin
      if (((I.f_eq_bits (I.bigint_of_string "32") (I.f_and_bits (I.bigint_of_string "32") (v_enc) (I.from_bitsLit "00100000000000001110000000000000")) (I.from_bitsLit "00100000000000001100000000000000")) || (I.f_eq_bits (I.bigint_of_string "32") (I.f_and_bits (I.bigint_of_string "32") (v_enc) (I.from_bitsLit "00100000000000001001000000000000")) (I.from_bitsLit "00100000000000000000000000000000"))) || (I.f_eq_bits (I.bigint_of_string "32") (I.f_and_bits (I.bigint_of_string "32") (v_enc) (I.from_bitsLit "00100000000000000101000000000000")) (I.from_bitsLit "00100000000000000000000000000000"))) || (I.f_eq_bits (I.bigint_of_string "32") (I.f_and_bits (I.bigint_of_string "32") (v_enc) (I.from_bitsLit "00100000000000000011000000000000")) (I.from_bitsLit "00100000000000000000000000000000")) then begin
        I.f_gen_store (v_result__1) (I.f_gen_bit_lit (I.bigint_of_string "128") (I.f_not_bits (I.bigint_of_string "128") (I.f_replicate_bits (I.bigint_of_string "64") (I.bigint_of_string "2") (!v_imm64__2) (I.bigint_of_string "2"))))
      end else begin
        if (I.f_eq_bits (I.bigint_of_string "32") (I.f_and_bits (I.bigint_of_string "32") (v_enc) (I.from_bitsLit "00100000000000001001000000000000")) (I.from_bitsLit "00000000000000000001000000000000")) || (I.f_eq_bits (I.bigint_of_string "32") (I.f_and_bits (I.bigint_of_string "32") (v_enc) (I.from_bitsLit "00100000000000000101000000000000")) (I.from_bitsLit "00000000000000000001000000000000")) then begin
          I.f_gen_store (v_result__1) (I.f_gen_or_bits (I.bigint_of_string "128") (I.f_gen_array_load (I.v__Z) (I.f_cvt_bits_uint (I.bigint_of_string "5") (I.extract_bits (v_enc) (I.bigint_of_string "0") (I.bigint_of_string "5")))) (I.f_gen_bit_lit (I.bigint_mul (I.bigint_of_string "64") (I.bigint_of_string "2")) (I.f_replicate_bits (I.bigint_of_string "64") (I.bigint_of_string "2") (!v_imm64__2) (I.bigint_of_string "2"))))
        end else begin
          I.f_gen_store (v_result__1) (I.f_gen_and_bits (I.bigint_of_string "128") (I.f_gen_array_load (I.v__Z) (I.f_cvt_bits_uint (I.bigint_of_string "5") (I.extract_bits (v_enc) (I.bigint_of_string "0") (I.bigint_of_string "5")))) (I.f_gen_bit_lit (I.bigint_of_string "128") (I.f_not_bits (I.bigint_of_string "128") (I.f_replicate_bits (I.bigint_of_string "64") (I.bigint_of_string "2") (!v_imm64__2) (I.bigint_of_string "2")))))
        end
      end
    end;
    I.f_gen_array_store (I.v__Z) (I.f_cvt_bits_uint (I.bigint_of_string "5") (I.extract_bits (v_enc) (I.bigint_of_string "0") (I.bigint_of_string "5"))) (I.f_gen_load (v_result__1))
  end else begin
    let v_imm64__2_1 = ref (I.mkBits (I.bigint_of_string "64") I.bigint_zero) in
    if I.f_eq_bits (I.bigint_of_string "32") (I.f_and_bits (I.bigint_of_string "32") (v_enc) (I.from_bitsLit "00000000000000001110000000000000")) (I.from_bitsLit "00000000000000000000000000000000") then begin
      v_imm64__2_1 := I.f_replicate_bits (I.bigint_of_string "32") (I.bigint_of_string "2") (I.f_append_bits (I.bigint_of_string "24") (I.bigint_of_string "8") (I.from_bitsLit "000000000000000000000000") (I.f_append_bits (I.bigint_of_string "7") (I.bigint_of_string "1") (I.f_append_bits (I.bigint_of_string "6") (I.bigint_of_string "1") (I.f_append_bits (I.bigint_of_string "5") (I.bigint_of_string "1") (I.f_append_bits (I.bigint_of_string "4") (I.bigint_of_string "1") (I.f_append_bits (I.bigint_of_string "3") (I.bigint_of_string "1") (I.f_append_bits (I.bigint_of_string "2") (I.bigint_of_string "1") (I.f_append_bits (I.bigint_of_string "1") (I.bigint_of_string "1") (I.extract_bits (v_enc) (I.bigint_of_string "18") (I.bigint_of_string "1")) (I.extract_bits (v_enc) (I.bigint_of_string "17") (I.bigint_of_string "1"))) (I.extract_bits (v_enc) (I.bigint_of_string "16") (I.bigint_of_string "1"))) (I.extract_bits (v_enc) (I.bigint_of_string "9") (I.bigint_of_string "1"))) (I.extract_bits (v_enc) (I.bigint_of_string "8") (I.bigint_of_string "1"))) (I.extract_bits (v_enc) (I.bigint_of_string "7") (I.bigint_of_string "1"))) (I.extract_bits (v_enc) (I.bigint_of_string "6") (I.bigint_of_string "1"))) (I.extract_bits (v_enc) (I.bigint_of_string "5") (I.bigint_of_string "1")))) (I.bigint_of_string "2")
    end else begin
      if I.f_eq_bits (I.bigint_of_string "32") (I.f_and_bits (I.bigint_of_string "32") (v_enc) (I.from_bitsLit "00000000000000001110000000000000")) (I.from_bitsLit "00000000000000000010000000000000") then begin
        v_imm64__2_1 := I.f_replicate_bits (I.bigint_of_string "32") (I.bigint_of_string "2") (I.f_append_bits (I.bigint_of_string "24") (I.bigint_of_string "8") (I.f_append_bits (I.bigint_of_string "16") (I.bigint_of_string "8") (I.from_bitsLit "0000000000000000") (I.f_append_bits (I.bigint_of_string "7") (I.bigint_of_string "1") (I.f_append_bits (I.bigint_of_string "6") (I.bigint_of_string "1") (I.f_append_bits (I.bigint_of_string "5") (I.bigint_of_string "1") (I.f_append_bits (I.bigint_of_string "4") (I.bigint_of_string "1") (I.f_append_bits (I.bigint_of_string "3") (I.bigint_of_string "1") (I.f_append_bits (I.bigint_of_string "2") (I.bigint_of_string "1") (I.f_append_bits (I.bigint_of_string "1") (I.bigint_of_string "1") (I.extract_bits (v_enc) (I.bigint_of_string "18") (I.bigint_of_string "1")) (I.extract_bits (v_enc) (I.bigint_of_string "17") (I.bigint_of_string "1"))) (I.extract_bits (v_enc) (I.bigint_of_string "16") (I.bigint_of_string "1"))) (I.extract_bits (v_enc) (I.bigint_of_string "9") (I.bigint_of_string "1"))) (I.extract_bits (v_enc) (I.bigint_of_string "8") (I.bigint_of_string "1"))) (I.extract_bits (v_enc) (I.bigint_of_string "7") (I.bigint_of_string "1"))) (I.extract_bits (v_enc) (I.bigint_of_string "6") (I.bigint_of_string "1"))) (I.extract_bits (v_enc) (I.bigint_of_string "5") (I.bigint_of_string "1")))) (I.from_bitsLit "00000000")) (I.bigint_of_string "2")
      end else begin
        if I.f_eq_bits (I.bigint_of_string "32") (I.f_and_bits (I.bigint_of_string "32") (v_enc) (I.from_bitsLit "00000000000000001110000000000000")) (I.from_bitsLit "00000000000000000100000000000000") then begin
          v_imm64__2_1 := I.f_replicate_bits (I.bigint_of_string "32") (I.bigint_of_string "2") (I.f_append_bits (I.bigint_of_string "16") (I.bigint_of_string "16") (I.f_append_bits (I.bigint_of_string "8") (I.bigint_of_string "8") (I.from_bitsLit "00000000") (I.f_append_bits (I.bigint_of_string "7") (I.bigint_of_string "1") (I.f_append_bits (I.bigint_of_string "6") (I.bigint_of_string "1") (I.f_append_bits (I.bigint_of_string "5") (I.bigint_of_string "1") (I.f_append_bits (I.bigint_of_string "4") (I.bigint_of_string "1") (I.f_append_bits (I.bigint_of_string "3") (I.bigint_of_string "1") (I.f_append_bits (I.bigint_of_string "2") (I.bigint_of_string "1") (I.f_append_bits (I.bigint_of_string "1") (I.bigint_of_string "1") (I.extract_bits (v_enc) (I.bigint_of_string "18") (I.bigint_of_string "1")) (I.extract_bits (v_enc) (I.bigint_of_string "17") (I.bigint_of_string "1"))) (I.extract_bits (v_enc) (I.bigint_of_string "16") (I.bigint_of_string "1"))) (I.extract_bits (v_enc) (I.bigint_of_string "9") (I.bigint_of_string "1"))) (I.extract_bits (v_enc) (I.bigint_of_string "8") (I.bigint_of_string "1"))) (I.extract_bits (v_enc) (I.bigint_of_string "7") (I.bigint_of_string "1"))) (I.extract_bits (v_enc) (I.bigint_of_string "6") (I.bigint_of_string "1"))) (I.extract_bits (v_enc) (I.bigint_of_string "5") (I.bigint_of_string "1")))) (I.from_bitsLit "0000000000000000")) (I.bigint_of_string "2")
        end else begin
          if I.f_eq_bits (I.bigint_of_string "32") (I.f_and_bits (I.bigint_of_string "32") (v_enc) (I.from_bitsLit "00000000000000001110000000000000")) (I.from_bitsLit "00000000000000000110000000000000") then begin
            v_imm64__2_1 := I.f_replicate_bits (I.bigint_of_string "32") (I.bigint_of_string "2") (I.f_append_bits (I.bigint_of_string "8") (I.bigint_of_string "24") (I.f_append_bits (I.bigint_of_string "7") (I.bigint_of_string "1") (I.f_append_bits (I.bigint_of_string "6") (I.bigint_of_string "1") (I.f_append_bits (I.bigint_of_string "5") (I.bigint_of_string "1") (I.f_append_bits (I.bigint_of_string "4") (I.bigint_of_string "1") (I.f_append_bits (I.bigint_of_string "3") (I.bigint_of_string "1") (I.f_append_bits (I.bigint_of_string "2") (I.bigint_of_string "1") (I.f_append_bits (I.bigint_of_string "1") (I.bigint_of_string "1") (I.extract_bits (v_enc) (I.bigint_of_string "18") (I.bigint_of_string "1")) (I.extract_bits (v_enc) (I.bigint_of_string "17") (I.bigint_of_string "1"))) (I.extract_bits (v_enc) (I.bigint_of_string "16") (I.bigint_of_string "1"))) (I.extract_bits (v_enc) (I.bigint_of_string "9") (I.bigint_of_string "1"))) (I.extract_bits (v_enc) (I.bigint_of_string "8") (I.bigint_of_string "1"))) (I.extract_bits (v_enc) (I.bigint_of_string "7") (I.bigint_of_string "1"))) (I.extract_bits (v_enc) (I.bigint_of_string "6") (I.bigint_of_string "1"))) (I.extract_bits (v_enc) (I.bigint_of_string "5") (I.bigint_of_string "1"))) (I.from_bitsLit "000000000000000000000000")) (I.bigint_of_string "2")
          end else begin
            if I.f_eq_bits (I.bigint_of_string "32") (I.f_and_bits (I.bigint_of_string "32") (v_enc) (I.from_bitsLit "00000000000000001110000000000000")) (I.from_bitsLit "00000000000000001000000000000000") then begin
              v_imm64__2_1 := I.f_replicate_bits (I.bigint_of_string "16") (I.bigint_of_string "4") (I.f_append_bits (I.bigint_of_string "8") (I.bigint_of_string "8") (I.from_bitsLit "00000000") (I.f_append_bits (I.bigint_of_string "7") (I.bigint_of_string "1") (I.f_append_bits (I.bigint_of_string "6") (I.bigint_of_string "1") (I.f_append_bits (I.bigint_of_string "5") (I.bigint_of_string "1") (I.f_append_bits (I.bigint_of_string "4") (I.bigint_of_string "1") (I.f_append_bits (I.bigint_of_string "3") (I.bigint_of_string "1") (I.f_append_bits (I.bigint_of_string "2") (I.bigint_of_string "1") (I.f_append_bits (I.bigint_of_string "1") (I.bigint_of_string "1") (I.extract_bits (v_enc) (I.bigint_of_string "18") (I.bigint_of_string "1")) (I.extract_bits (v_enc) (I.bigint_of_string "17") (I.bigint_of_string "1"))) (I.extract_bits (v_enc) (I.bigint_of_string "16") (I.bigint_of_string "1"))) (I.extract_bits (v_enc) (I.bigint_of_string "9") (I.bigint_of_string "1"))) (I.extract_bits (v_enc) (I.bigint_of_string "8") (I.bigint_of_string "1"))) (I.extract_bits (v_enc) (I.bigint_of_string "7") (I.bigint_of_string "1"))) (I.extract_bits (v_enc) (I.bigint_of_string "6") (I.bigint_of_string "1"))) (I.extract_bits (v_enc) (I.bigint_of_string "5") (I.bigint_of_string "1")))) (I.bigint_of_string "4")
            end else begin
              if I.f_eq_bits (I.bigint_of_string "32") (I.f_and_bits (I.bigint_of_string "32") (v_enc) (I.from_bitsLit "00000000000000001110000000000000")) (I.from_bitsLit "00000000000000001010000000000000") then begin
                v_imm64__2_1 := I.f_replicate_bits (I.bigint_of_string "16") (I.bigint_of_string "4") (I.f_append_bits (I.bigint_of_string "8") (I.bigint_of_string "8") (I.f_append_bits (I.bigint_of_string "7") (I.bigint_of_string "1") (I.f_append_bits (I.bigint_of_string "6") (I.bigint_of_string "1") (I.f_append_bits (I.bigint_of_string "5") (I.bigint_of_string "1") (I.f_append_bits (I.bigint_of_string "4") (I.bigint_of_string "1") (I.f_append_bits (I.bigint_of_string "3") (I.bigint_of_string "1") (I.f_append_bits (I.bigint_of_string "2") (I.bigint_of_string "1") (I.f_append_bits (I.bigint_of_string "1") (I.bigint_of_string "1") (I.extract_bits (v_enc) (I.bigint_of_string "18") (I.bigint_of_string "1")) (I.extract_bits (v_enc) (I.bigint_of_string "17") (I.bigint_of_string "1"))) (I.extract_bits (v_enc) (I.bigint_of_string "16") (I.bigint_of_string "1"))) (I.extract_bits (v_enc) (I.bigint_of_string "9") (I.bigint_of_string "1"))) (I.extract_bits (v_enc) (I.bigint_of_string "8") (I.bigint_of_string "1"))) (I.extract_bits (v_enc) (I.bigint_of_string "7") (I.bigint_of_string "1"))) (I.extract_bits (v_enc) (I.bigint_of_string "6") (I.bigint_of_string "1"))) (I.extract_bits (v_enc) (I.bigint_of_string "5") (I.bigint_of_string "1"))) (I.from_bitsLit "00000000")) (I.bigint_of_string "4")
              end else begin
                if I.f_eq_bits (I.bigint_of_string "32") (I.f_and_bits (I.bigint_of_string "32") (v_enc) (I.from_bitsLit "00000000000000001110000000000000")) (I.from_bitsLit "00000000000000001100000000000000") then begin
                  if I.f_eq_bits (I.bigint_of_string "32") (I.f_and_bits (I.bigint_of_string "32") (v_enc) (I.from_bitsLit "00000000000000000001000000000000")) (I.from_bitsLit "00000000000000000000000000000000") then begin
                    v_imm64__2_1 := I.f_replicate_bits (I.bigint_of_string "32") (I.bigint_of_string "2") (I.f_append_bits (I.bigint_of_string "24") (I.bigint_of_string "8") (I.f_append_bits (I.bigint_of_string "16") (I.bigint_of_string "8") (I.from_bitsLit "0000000000000000") (I.f_append_bits (I.bigint_of_string "7") (I.bigint_of_string "1") (I.f_append_bits (I.bigint_of_string "6") (I.bigint_of_string "1") (I.f_append_bits (I.bigint_of_string "5") (I.bigint_of_string "1") (I.f_append_bits (I.bigint_of_string "4") (I.bigint_of_string "1") (I.f_append_bits (I.bigint_of_string "3") (I.bigint_of_string "1") (I.f_append_bits (I.bigint_of_string "2") (I.bigint_of_string "1") (I.f_append_bits (I.bigint_of_string "1") (I.bigint_of_string "1") (I.extract_bits (v_enc) (I.bigint_of_string "18") (I.bigint_of_string "1")) (I.extract_bits (v_enc) (I.bigint_of_string "17") (I.bigint_of_string "1"))) (I.extract_bits (v_enc) (I.bigint_of_string "16") (I.bigint_of_string "1"))) (I.extract_bits (v_enc) (I.bigint_of_string "9") (I.bigint_of_string "1"))) (I.extract_bits (v_enc) (I.bigint_of_string "8") (I.bigint_of_string "1"))) (I.extract_bits (v_enc) (I.bigint_of_string "7") (I.bigint_of_string "1"))) (I.extract_bits (v_enc) (I.bigint_of_string "6") (I.bigint_of_string "1"))) (I.extract_bits (v_enc) (I.bigint_of_string "5") (I.bigint_of_string "1")))) (I.from_bitsLit "11111111")) (I.bigint_of_string "2")
                  end else begin
                    v_imm64__2_1 := I.f_replicate_bits (I.bigint_of_string "32") (I.bigint_of_string "2") (I.f_append_bits (I.bigint_of_string "16") (I.bigint_of_string "16") (I.f_append_bits (I.bigint_of_string "8") (I.bigint_of_string "8") (I.from_bitsLit "00000000") (I.f_append_bits (I.bigint_of_string "7") (I.bigint_of_string "1") (I.f_append_bits (I.bigint_of_string "6") (I.bigint_of_string "1") (I.f_append_bits (I.bigint_of_string "5") (I.bigint_of_string "1") (I.f_append_bits (I.bigint_of_string "4") (I.bigint_of_string "1") (I.f_append_bits (I.bigint_of_string "3") (I.bigint_of_string "1") (I.f_append_bits (I.bigint_of_string "2") (I.bigint_of_string "1") (I.f_append_bits (I.bigint_of_string "1") (I.bigint_of_string "1") (I.extract_bits (v_enc) (I.bigint_of_string "18") (I.bigint_of_string "1")) (I.extract_bits (v_enc) (I.bigint_of_string "17") (I.bigint_of_string "1"))) (I.extract_bits (v_enc) (I.bigint_of_string "16") (I.bigint_of_string "1"))) (I.extract_bits (v_enc) (I.bigint_of_string "9") (I.bigint_of_string "1"))) (I.extract_bits (v_enc) (I.bigint_of_string "8") (I.bigint_of_string "1"))) (I.extract_bits (v_enc) (I.bigint_of_string "7") (I.bigint_of_string "1"))) (I.extract_bits (v_enc) (I.bigint_of_string "6") (I.bigint_of_string "1"))) (I.extract_bits (v_enc) (I.bigint_of_string "5") (I.bigint_of_string "1")))) (I.from_bitsLit "1111111111111111")) (I.bigint_of_string "2")
                  end
                end else begin
                  if I.f_eq_bits (I.bigint_of_string "32") (I.f_and_bits (I.bigint_of_string "32") (v_enc) (I.from_bitsLit "00100000000000000001000000000000")) (I.from_bitsLit "00000000000000000000000000000000") then begin
                    v_imm64__2_1 := I.f_replicate_bits (I.bigint_of_string "8") (I.bigint_of_string "8") (I.f_append_bits (I.bigint_of_string "7") (I.bigint_of_string "1") (I.f_append_bits (I.bigint_of_string "6") (I.bigint_of_string "1") (I.f_append_bits (I.bigint_of_string "5") (I.bigint_of_string "1") (I.f_append_bits (I.bigint_of_string "4") (I.bigint_of_string "1") (I.f_append_bits (I.bigint_of_string "3") (I.bigint_of_string "1") (I.f_append_bits (I.bigint_of_string "2") (I.bigint_of_string "1") (I.f_append_bits (I.bigint_of_string "1") (I.bigint_of_string "1") (I.extract_bits (v_enc) (I.bigint_of_string "18") (I.bigint_of_string "1")) (I.extract_bits (v_enc) (I.bigint_of_string "17") (I.bigint_of_string "1"))) (I.extract_bits (v_enc) (I.bigint_of_string "16") (I.bigint_of_string "1"))) (I.extract_bits (v_enc) (I.bigint_of_string "9") (I.bigint_of_string "1"))) (I.extract_bits (v_enc) (I.bigint_of_string "8") (I.bigint_of_string "1"))) (I.extract_bits (v_enc) (I.bigint_of_string "7") (I.bigint_of_string "1"))) (I.extract_bits (v_enc) (I.bigint_of_string "6") (I.bigint_of_string "1"))) (I.extract_bits (v_enc) (I.bigint_of_string "5") (I.bigint_of_string "1"))) (I.bigint_of_string "8")
                  end else begin
                    if I.f_eq_bits (I.bigint_of_string "32") (I.f_and_bits (I.bigint_of_string "32") (v_enc) (I.from_bitsLit "00100000000000000001000000000000")) (I.from_bitsLit "00100000000000000000000000000000") then begin
                      v_imm64__2_1 := I.f_append_bits (I.bigint_of_string "56") (I.bigint_of_string "8") (I.f_append_bits (I.bigint_of_string "48") (I.bigint_of_string "8") (I.f_append_bits (I.bigint_of_string "40") (I.bigint_of_string "8") (I.f_append_bits (I.bigint_of_string "32") (I.bigint_of_string "8") (I.f_append_bits (I.bigint_of_string "24") (I.bigint_of_string "8") (I.f_append_bits (I.bigint_of_string "16") (I.bigint_of_string "8") (I.f_append_bits (I.bigint_of_string "8") (I.bigint_of_string "8") (I.f_replicate_bits (I.bigint_of_string "1") (I.bigint_of_string "8") (I.extract_bits (v_enc) (I.bigint_of_string "18") (I.bigint_of_string "1")) (I.bigint_of_string "8")) (I.f_replicate_bits (I.bigint_of_string "1") (I.bigint_of_string "8") (I.extract_bits (v_enc) (I.bigint_of_string "17") (I.bigint_of_string "1")) (I.bigint_of_string "8"))) (I.f_replicate_bits (I.bigint_of_string "1") (I.bigint_of_string "8") (I.extract_bits (v_enc) (I.bigint_of_string "16") (I.bigint_of_string "1")) (I.bigint_of_string "8"))) (I.f_replicate_bits (I.bigint_of_string "1") (I.bigint_of_string "8") (I.extract_bits (v_enc) (I.bigint_of_string "9") (I.bigint_of_string "1")) (I.bigint_of_string "8"))) (I.f_replicate_bits (I.bigint_of_string "1") (I.bigint_of_string "8") (I.extract_bits (v_enc) (I.bigint_of_string "8") (I.bigint_of_string "1")) (I.bigint_of_string "8"))) (I.f_replicate_bits (I.bigint_of_string "1") (I.bigint_of_string "8") (I.extract_bits (v_enc) (I.bigint_of_string "7") (I.bigint_of_string "1")) (I.bigint_of_string "8"))) (I.f_replicate_bits (I.bigint_of_string "1") (I.bigint_of_string "8") (I.extract_bits (v_enc) (I.bigint_of_string "6") (I.bigint_of_string "1")) (I.bigint_of_string "8"))) (I.f_replicate_bits (I.bigint_of_string "1") (I.bigint_of_string "8") (I.extract_bits (v_enc) (I.bigint_of_string "5") (I.bigint_of_string "1")) (I.bigint_of_string "8"))
                    end else begin
                      v_imm64__2_1 := I.f_replicate_bits (I.bigint_of_string "32") (I.bigint_of_string "2") (I.f_append_bits (I.bigint_of_string "13") (I.bigint_of_string "19") (I.f_append_bits (I.bigint_of_string "7") (I.bigint_of_string "6") (I.f_append_bits (I.bigint_of_string "2") (I.bigint_of_string "5") (I.f_append_bits (I.bigint_of_string "1") (I.bigint_of_string "1") (I.extract_bits (v_enc) (I.bigint_of_string "18") (I.bigint_of_string "1")) (I.f_not_bits (I.bigint_of_string "1") (I.extract_bits (v_enc) (I.bigint_of_string "17") (I.bigint_of_string "1")))) (I.f_replicate_bits (I.bigint_of_string "1") (I.bigint_of_string "5") (I.extract_bits (v_enc) (I.bigint_of_string "17") (I.bigint_of_string "1")) (I.bigint_of_string "5"))) (I.f_append_bits (I.bigint_of_string "5") (I.bigint_of_string "1") (I.f_append_bits (I.bigint_of_string "4") (I.bigint_of_string "1") (I.f_append_bits (I.bigint_of_string "3") (I.bigint_of_string "1") (I.f_append_bits (I.bigint_of_string "2") (I.bigint_of_string "1") (I.f_append_bits (I.bigint_of_string "1") (I.bigint_of_string "1") (I.extract_bits (v_enc) (I.bigint_of_string "16") (I.bigint_of_string "1")) (I.extract_bits (v_enc) (I.bigint_of_string "9") (I.bigint_of_string "1"))) (I.extract_bits (v_enc) (I.bigint_of_string "8") (I.bigint_of_string "1"))) (I.extract_bits (v_enc) (I.bigint_of_string "7") (I.bigint_of_string "1"))) (I.extract_bits (v_enc) (I.bigint_of_string "6") (I.bigint_of_string "1"))) (I.extract_bits (v_enc) (I.bigint_of_string "5") (I.bigint_of_string "1")))) (I.from_bitsLit "0000000000000000000")) (I.bigint_of_string "2")
                    end
                  end
                end
              end
            end
          end
        end
      end
    end;
    let v_result__1_1 = I.f_decl_bv ("result__1_1") (I.bigint_of_string "64") in
    if ((I.f_eq_bits (I.bigint_of_string "32") (I.f_and_bits (I.bigint_of_string "32") (v_enc) (I.from_bitsLit "00100000000000001100000000000000")) (I.from_bitsLit "00000000000000001100000000000000")) || (I.f_eq_bits (I.bigint_of_string "32") (I.f_and_bits (I.bigint_of_string "32") (v_enc) (I.from_bitsLit "00000000000000001110000000000000")) (I.from_bitsLit "00000000000000001110000000000000"))) || (I.f_eq_bits (I.bigint_of_string "32") (I.f_and_bits (I.bigint_of_string "32") (v_enc) (I.from_bitsLit "00100000000000000001000000000000")) (I.from_bitsLit "00000000000000000000000000000000")) then begin
      I.f_gen_store (v_result__1_1) (I.f_gen_bit_lit (I.bigint_mul (I.bigint_of_string "64") (I.bigint_of_string "1")) (I.f_replicate_bits (I.bigint_of_string "64") (I.bigint_of_string "1") (!v_imm64__2_1) (I.bigint_of_string "1")))
    end else begin
      if (((I.f_eq_bits (I.bigint_of_string "32") (I.f_and_bits (I.bigint_of_string "32") (v_enc) (I.from_bitsLit "00100000000000001110000000000000")) (I.from_bitsLit "00100000000000001100000000000000")) || (I.f_eq_bits (I.bigint_of_string "32") (I.f_and_bits (I.bigint_of_string "32") (v_enc) (I.from_bitsLit "00100000000000001001000000000000")) (I.from_bitsLit "00100000000000000000000000000000"))) || (I.f_eq_bits (I.bigint_of_string "32") (I.f_and_bits (I.bigint_of_string "32") (v_enc) (I.from_bitsLit "00100000000000000101000000000000")) (I.from_bitsLit "00100000000000000000000000000000"))) || (I.f_eq_bits (I.bigint_of_string "32") (I.f_and_bits (I.bigint_of_string "32") (v_enc) (I.from_bitsLit "00100000000000000011000000000000")) (I.from_bitsLit "00100000000000000000000000000000")) then begin
        I.f_gen_store (v_result__1_1) (I.f_gen_bit_lit (I.bigint_of_string "64") (I.f_not_bits (I.bigint_of_string "64") (I.f_replicate_bits (I.bigint_of_string "64") (I.bigint_of_string "1") (!v_imm64__2_1) (I.bigint_of_string "1"))))
      end else begin
        if (I.f_eq_bits (I.bigint_of_string "32") (I.f_and_bits (I.bigint_of_string "32") (v_enc) (I.from_bitsLit "00100000000000001001000000000000")) (I.from_bitsLit "00000000000000000001000000000000")) || (I.f_eq_bits (I.bigint_of_string "32") (I.f_and_bits (I.bigint_of_string "32") (v_enc) (I.from_bitsLit "00100000000000000101000000000000")) (I.from_bitsLit "00000000000000000001000000000000")) then begin
          I.f_gen_store (v_result__1_1) (I.f_gen_or_bits (I.bigint_of_string "64") (I.f_gen_slice (I.f_gen_array_load (I.v__Z) (I.f_cvt_bits_uint (I.bigint_of_string "5") (I.extract_bits (v_enc) (I.bigint_of_string "0") (I.bigint_of_string "5")))) (I.bigint_of_string "0") (I.bigint_of_string "64")) (I.f_gen_bit_lit (I.bigint_mul (I.bigint_of_string "64") (I.bigint_of_string "1")) (I.f_replicate_bits (I.bigint_of_string "64") (I.bigint_of_string "1") (!v_imm64__2_1) (I.bigint_of_string "1"))))
        end else begin
          I.f_gen_store (v_result__1_1) (I.f_gen_and_bits (I.bigint_of_string "64") (I.f_gen_slice (I.f_gen_array_load (I.v__Z) (I.f_cvt_bits_uint (I.bigint_of_string "5") (I.extract_bits (v_enc) (I.bigint_of_string "0") (I.bigint_of_string "5")))) (I.bigint_of_string "0") (I.bigint_of_string "64")) (I.f_gen_bit_lit (I.bigint_of_string "64") (I.f_not_bits (I.bigint_of_string "64") (I.f_replicate_bits (I.bigint_of_string "64") (I.bigint_of_string "1") (!v_imm64__2_1) (I.bigint_of_string "1")))))
        end
      end
    end;
    I.f_gen_array_store (I.v__Z) (I.f_cvt_bits_uint (I.bigint_of_string "5") (I.extract_bits (v_enc) (I.bigint_of_string "0") (I.bigint_of_string "5"))) (I.f_gen_ZeroExtend (I.bigint_of_string "64") (I.bigint_of_string "128") (I.f_gen_load (v_result__1_1)) (I.f_gen_int_lit (I.bigint_of_string "128")))
  end

