(* AUTO-GENERATED LIFTER FILE *)

open Instruction_building_interface

let f_aarch64_vector_arithmetic_binary_uniform_mul_fp_mul_norounding_lower (type bitvector) (module I : IBI with type bitvector = bitvector) (v_enc : bitvector) : unit = 
  if I.f_eq_bits (I.bigint_of_string "32") (I.f_and_bits (I.bigint_of_string "32") (v_enc) (I.from_bitsLit "01000000000000000000000000000000")) (I.from_bitsLit "01000000000000000000000000000000") then begin
    let v_Exp11__3 = I.f_decl_bv ("Exp11__3") (I.bigint_of_string "128") in
    I.f_gen_store (v_Exp11__3) (I.f_gen_array_load (I.v__Z) (I.f_cvt_bits_uint (I.bigint_of_string "5") (I.extract_bits (v_enc) (I.bigint_of_string "5") (I.bigint_of_string "5"))));
    let v_Exp16__3 = I.f_decl_bv ("Exp16__3") (I.bigint_of_string "128") in
    I.f_gen_store (v_Exp16__3) (I.f_gen_array_load (I.v__Z) (I.f_cvt_bits_uint (I.bigint_of_string "5") (I.extract_bits (v_enc) (I.bigint_of_string "16") (I.bigint_of_string "5"))));
    let v_Exp19__2 = I.f_decl_bv ("Exp19__2") (I.bigint_of_string "128") in
    I.f_gen_store (v_Exp19__2) (I.f_gen_array_load (I.v__Z) (I.f_cvt_bits_uint (I.bigint_of_string "5") (I.extract_bits (v_enc) (I.bigint_of_string "0") (I.bigint_of_string "5"))));
    let v_result__1 = I.f_decl_bv ("result__1") (I.bigint_of_string "128") in
    if I.f_eq_bits (I.bigint_of_string "32") (I.f_and_bits (I.bigint_of_string "32") (v_enc) (I.from_bitsLit "00000000100000000000000000000000")) (I.from_bitsLit "00000000100000000000000000000000") then begin
      let v_Exp26__2 = I.f_decl_bv ("Exp26__2") (I.bigint_of_string "32") in
      I.f_gen_store (v_Exp26__2) (I.f_gen_FPMulAddH (I.bigint_of_string "32") (I.f_gen_slice (I.f_gen_array_load (I.v__Z) (I.f_cvt_bits_uint (I.bigint_of_string "5") (I.extract_bits (v_enc) (I.bigint_of_string "0") (I.bigint_of_string "5")))) (I.bigint_of_string "0") (I.bigint_of_string "32")) (I.f_gen_append_bits (I.bigint_of_string "1") (I.bigint_of_string "15") (I.f_gen_not_bits (I.bigint_of_string "1") (I.f_gen_slice (I.f_gen_array_load (I.v__Z) (I.f_cvt_bits_uint (I.bigint_of_string "5") (I.extract_bits (v_enc) (I.bigint_of_string "5") (I.bigint_of_string "5")))) (I.bigint_of_string "15") (I.bigint_of_string "1"))) (I.f_gen_slice (I.f_gen_array_load (I.v__Z) (I.f_cvt_bits_uint (I.bigint_of_string "5") (I.extract_bits (v_enc) (I.bigint_of_string "5") (I.bigint_of_string "5")))) (I.bigint_of_string "0") (I.bigint_of_string "15"))) (I.f_gen_slice (I.f_gen_array_load (I.v__Z) (I.f_cvt_bits_uint (I.bigint_of_string "5") (I.extract_bits (v_enc) (I.bigint_of_string "16") (I.bigint_of_string "5")))) (I.bigint_of_string "0") (I.bigint_of_string "16")) (I.f_gen_load (I.v_FPCR)));
      I.f_gen_store (v_result__1) (I.f_gen_append_bits (I.bigint_of_string "96") (I.bigint_of_string "32") (I.f_gen_slice (I.f_gen_load (v_result__1)) (I.bigint_of_string "32") (I.bigint_of_string "96")) (I.f_gen_load (v_Exp26__2)))
    end else begin
      let v_Exp31__2 = I.f_decl_bv ("Exp31__2") (I.bigint_of_string "32") in
      I.f_gen_store (v_Exp31__2) (I.f_gen_FPMulAddH (I.bigint_of_string "32") (I.f_gen_slice (I.f_gen_array_load (I.v__Z) (I.f_cvt_bits_uint (I.bigint_of_string "5") (I.extract_bits (v_enc) (I.bigint_of_string "0") (I.bigint_of_string "5")))) (I.bigint_of_string "0") (I.bigint_of_string "32")) (I.f_gen_slice (I.f_gen_array_load (I.v__Z) (I.f_cvt_bits_uint (I.bigint_of_string "5") (I.extract_bits (v_enc) (I.bigint_of_string "5") (I.bigint_of_string "5")))) (I.bigint_of_string "0") (I.bigint_of_string "16")) (I.f_gen_slice (I.f_gen_array_load (I.v__Z) (I.f_cvt_bits_uint (I.bigint_of_string "5") (I.extract_bits (v_enc) (I.bigint_of_string "16") (I.bigint_of_string "5")))) (I.bigint_of_string "0") (I.bigint_of_string "16")) (I.f_gen_load (I.v_FPCR)));
      I.f_gen_store (v_result__1) (I.f_gen_append_bits (I.bigint_of_string "96") (I.bigint_of_string "32") (I.f_gen_slice (I.f_gen_load (v_result__1)) (I.bigint_of_string "32") (I.bigint_of_string "96")) (I.f_gen_load (v_Exp31__2)))
    end;
    if I.f_eq_bits (I.bigint_of_string "32") (I.f_and_bits (I.bigint_of_string "32") (v_enc) (I.from_bitsLit "00000000100000000000000000000000")) (I.from_bitsLit "00000000100000000000000000000000") then begin
      let v_Exp39__2 = I.f_decl_bv ("Exp39__2") (I.bigint_of_string "32") in
      I.f_gen_store (v_Exp39__2) (I.f_gen_FPMulAddH (I.bigint_of_string "32") (I.f_gen_slice (I.f_gen_load (v_Exp19__2)) (I.bigint_of_string "32") (I.bigint_of_string "32")) (I.f_gen_append_bits (I.bigint_of_string "1") (I.bigint_of_string "15") (I.f_gen_not_bits (I.bigint_of_string "1") (I.f_gen_slice (I.f_gen_load (v_Exp11__3)) (I.bigint_of_string "31") (I.bigint_of_string "1"))) (I.f_gen_slice (I.f_gen_load (v_Exp11__3)) (I.bigint_of_string "16") (I.bigint_of_string "15"))) (I.f_gen_slice (I.f_gen_load (v_Exp16__3)) (I.bigint_of_string "16") (I.bigint_of_string "16")) (I.f_gen_load (I.v_FPCR)));
      I.f_gen_store (v_result__1) (I.f_gen_append_bits (I.bigint_of_string "64") (I.bigint_of_string "64") (I.f_gen_slice (I.f_gen_load (v_result__1)) (I.bigint_of_string "64") (I.bigint_of_string "64")) (I.f_gen_append_bits (I.bigint_of_string "32") (I.bigint_of_string "32") (I.f_gen_load (v_Exp39__2)) (I.f_gen_slice (I.f_gen_load (v_result__1)) (I.bigint_of_string "0") (I.bigint_of_string "32"))))
    end else begin
      let v_Exp44__2 = I.f_decl_bv ("Exp44__2") (I.bigint_of_string "32") in
      I.f_gen_store (v_Exp44__2) (I.f_gen_FPMulAddH (I.bigint_of_string "32") (I.f_gen_slice (I.f_gen_load (v_Exp19__2)) (I.bigint_of_string "32") (I.bigint_of_string "32")) (I.f_gen_slice (I.f_gen_load (v_Exp11__3)) (I.bigint_of_string "16") (I.bigint_of_string "16")) (I.f_gen_slice (I.f_gen_load (v_Exp16__3)) (I.bigint_of_string "16") (I.bigint_of_string "16")) (I.f_gen_load (I.v_FPCR)));
      I.f_gen_store (v_result__1) (I.f_gen_append_bits (I.bigint_of_string "64") (I.bigint_of_string "64") (I.f_gen_slice (I.f_gen_load (v_result__1)) (I.bigint_of_string "64") (I.bigint_of_string "64")) (I.f_gen_append_bits (I.bigint_of_string "32") (I.bigint_of_string "32") (I.f_gen_load (v_Exp44__2)) (I.f_gen_slice (I.f_gen_load (v_result__1)) (I.bigint_of_string "0") (I.bigint_of_string "32"))))
    end;
    if I.f_eq_bits (I.bigint_of_string "32") (I.f_and_bits (I.bigint_of_string "32") (v_enc) (I.from_bitsLit "00000000100000000000000000000000")) (I.from_bitsLit "00000000100000000000000000000000") then begin
      let v_Exp52__2 = I.f_decl_bv ("Exp52__2") (I.bigint_of_string "32") in
      I.f_gen_store (v_Exp52__2) (I.f_gen_FPMulAddH (I.bigint_of_string "32") (I.f_gen_slice (I.f_gen_load (v_Exp19__2)) (I.bigint_of_string "64") (I.bigint_of_string "32")) (I.f_gen_append_bits (I.bigint_of_string "1") (I.bigint_of_string "15") (I.f_gen_not_bits (I.bigint_of_string "1") (I.f_gen_slice (I.f_gen_load (v_Exp11__3)) (I.bigint_of_string "47") (I.bigint_of_string "1"))) (I.f_gen_slice (I.f_gen_load (v_Exp11__3)) (I.bigint_of_string "32") (I.bigint_of_string "15"))) (I.f_gen_slice (I.f_gen_load (v_Exp16__3)) (I.bigint_of_string "32") (I.bigint_of_string "16")) (I.f_gen_load (I.v_FPCR)));
      I.f_gen_store (v_result__1) (I.f_gen_append_bits (I.bigint_of_string "32") (I.bigint_of_string "96") (I.f_gen_slice (I.f_gen_load (v_result__1)) (I.bigint_of_string "96") (I.bigint_of_string "32")) (I.f_gen_append_bits (I.bigint_of_string "32") (I.bigint_of_string "64") (I.f_gen_load (v_Exp52__2)) (I.f_gen_slice (I.f_gen_load (v_result__1)) (I.bigint_of_string "0") (I.bigint_of_string "64"))))
    end else begin
      let v_Exp57__2 = I.f_decl_bv ("Exp57__2") (I.bigint_of_string "32") in
      I.f_gen_store (v_Exp57__2) (I.f_gen_FPMulAddH (I.bigint_of_string "32") (I.f_gen_slice (I.f_gen_load (v_Exp19__2)) (I.bigint_of_string "64") (I.bigint_of_string "32")) (I.f_gen_slice (I.f_gen_load (v_Exp11__3)) (I.bigint_of_string "32") (I.bigint_of_string "16")) (I.f_gen_slice (I.f_gen_load (v_Exp16__3)) (I.bigint_of_string "32") (I.bigint_of_string "16")) (I.f_gen_load (I.v_FPCR)));
      I.f_gen_store (v_result__1) (I.f_gen_append_bits (I.bigint_of_string "32") (I.bigint_of_string "96") (I.f_gen_slice (I.f_gen_load (v_result__1)) (I.bigint_of_string "96") (I.bigint_of_string "32")) (I.f_gen_append_bits (I.bigint_of_string "32") (I.bigint_of_string "64") (I.f_gen_load (v_Exp57__2)) (I.f_gen_slice (I.f_gen_load (v_result__1)) (I.bigint_of_string "0") (I.bigint_of_string "64"))))
    end;
    if I.f_eq_bits (I.bigint_of_string "32") (I.f_and_bits (I.bigint_of_string "32") (v_enc) (I.from_bitsLit "00000000100000000000000000000000")) (I.from_bitsLit "00000000100000000000000000000000") then begin
      let v_Exp65__2 = I.f_decl_bv ("Exp65__2") (I.bigint_of_string "32") in
      I.f_gen_store (v_Exp65__2) (I.f_gen_FPMulAddH (I.bigint_of_string "32") (I.f_gen_slice (I.f_gen_load (v_Exp19__2)) (I.bigint_of_string "96") (I.bigint_of_string "32")) (I.f_gen_append_bits (I.bigint_of_string "1") (I.bigint_of_string "15") (I.f_gen_not_bits (I.bigint_of_string "1") (I.f_gen_slice (I.f_gen_load (v_Exp11__3)) (I.bigint_of_string "63") (I.bigint_of_string "1"))) (I.f_gen_slice (I.f_gen_load (v_Exp11__3)) (I.bigint_of_string "48") (I.bigint_of_string "15"))) (I.f_gen_slice (I.f_gen_load (v_Exp16__3)) (I.bigint_of_string "48") (I.bigint_of_string "16")) (I.f_gen_load (I.v_FPCR)));
      I.f_gen_store (v_result__1) (I.f_gen_append_bits (I.bigint_of_string "32") (I.bigint_of_string "96") (I.f_gen_load (v_Exp65__2)) (I.f_gen_slice (I.f_gen_load (v_result__1)) (I.bigint_of_string "0") (I.bigint_of_string "96")))
    end else begin
      let v_Exp70__2 = I.f_decl_bv ("Exp70__2") (I.bigint_of_string "32") in
      I.f_gen_store (v_Exp70__2) (I.f_gen_FPMulAddH (I.bigint_of_string "32") (I.f_gen_slice (I.f_gen_load (v_Exp19__2)) (I.bigint_of_string "96") (I.bigint_of_string "32")) (I.f_gen_slice (I.f_gen_load (v_Exp11__3)) (I.bigint_of_string "48") (I.bigint_of_string "16")) (I.f_gen_slice (I.f_gen_load (v_Exp16__3)) (I.bigint_of_string "48") (I.bigint_of_string "16")) (I.f_gen_load (I.v_FPCR)));
      I.f_gen_store (v_result__1) (I.f_gen_append_bits (I.bigint_of_string "32") (I.bigint_of_string "96") (I.f_gen_load (v_Exp70__2)) (I.f_gen_slice (I.f_gen_load (v_result__1)) (I.bigint_of_string "0") (I.bigint_of_string "96")))
    end;
    I.f_gen_array_store (I.v__Z) (I.f_cvt_bits_uint (I.bigint_of_string "5") (I.extract_bits (v_enc) (I.bigint_of_string "0") (I.bigint_of_string "5"))) (I.f_gen_load (v_result__1))
  end else begin
    let v_Exp82__3 = I.f_decl_bv ("Exp82__3") (I.bigint_of_string "128") in
    I.f_gen_store (v_Exp82__3) (I.f_gen_array_load (I.v__Z) (I.f_cvt_bits_uint (I.bigint_of_string "5") (I.extract_bits (v_enc) (I.bigint_of_string "5") (I.bigint_of_string "5"))));
    let v_Exp87__3 = I.f_decl_bv ("Exp87__3") (I.bigint_of_string "128") in
    I.f_gen_store (v_Exp87__3) (I.f_gen_array_load (I.v__Z) (I.f_cvt_bits_uint (I.bigint_of_string "5") (I.extract_bits (v_enc) (I.bigint_of_string "16") (I.bigint_of_string "5"))));
    let v_Exp90__2 = I.f_decl_bv ("Exp90__2") (I.bigint_of_string "128") in
    I.f_gen_store (v_Exp90__2) (I.f_gen_array_load (I.v__Z) (I.f_cvt_bits_uint (I.bigint_of_string "5") (I.extract_bits (v_enc) (I.bigint_of_string "0") (I.bigint_of_string "5"))));
    let v_result__1_1 = I.f_decl_bv ("result__1_1") (I.bigint_of_string "64") in
    if I.f_eq_bits (I.bigint_of_string "32") (I.f_and_bits (I.bigint_of_string "32") (v_enc) (I.from_bitsLit "00000000100000000000000000000000")) (I.from_bitsLit "00000000100000000000000000000000") then begin
      let v_Exp97__2 = I.f_decl_bv ("Exp97__2") (I.bigint_of_string "32") in
      I.f_gen_store (v_Exp97__2) (I.f_gen_FPMulAddH (I.bigint_of_string "32") (I.f_gen_slice (I.f_gen_array_load (I.v__Z) (I.f_cvt_bits_uint (I.bigint_of_string "5") (I.extract_bits (v_enc) (I.bigint_of_string "0") (I.bigint_of_string "5")))) (I.bigint_of_string "0") (I.bigint_of_string "32")) (I.f_gen_append_bits (I.bigint_of_string "1") (I.bigint_of_string "15") (I.f_gen_not_bits (I.bigint_of_string "1") (I.f_gen_slice (I.f_gen_array_load (I.v__Z) (I.f_cvt_bits_uint (I.bigint_of_string "5") (I.extract_bits (v_enc) (I.bigint_of_string "5") (I.bigint_of_string "5")))) (I.bigint_of_string "15") (I.bigint_of_string "1"))) (I.f_gen_slice (I.f_gen_array_load (I.v__Z) (I.f_cvt_bits_uint (I.bigint_of_string "5") (I.extract_bits (v_enc) (I.bigint_of_string "5") (I.bigint_of_string "5")))) (I.bigint_of_string "0") (I.bigint_of_string "15"))) (I.f_gen_slice (I.f_gen_array_load (I.v__Z) (I.f_cvt_bits_uint (I.bigint_of_string "5") (I.extract_bits (v_enc) (I.bigint_of_string "16") (I.bigint_of_string "5")))) (I.bigint_of_string "0") (I.bigint_of_string "16")) (I.f_gen_load (I.v_FPCR)));
      I.f_gen_store (v_result__1_1) (I.f_gen_append_bits (I.bigint_of_string "32") (I.bigint_of_string "32") (I.f_gen_slice (I.f_gen_load (v_result__1_1)) (I.bigint_of_string "32") (I.bigint_of_string "32")) (I.f_gen_load (v_Exp97__2)))
    end else begin
      let v_Exp102__2 = I.f_decl_bv ("Exp102__2") (I.bigint_of_string "32") in
      I.f_gen_store (v_Exp102__2) (I.f_gen_FPMulAddH (I.bigint_of_string "32") (I.f_gen_slice (I.f_gen_array_load (I.v__Z) (I.f_cvt_bits_uint (I.bigint_of_string "5") (I.extract_bits (v_enc) (I.bigint_of_string "0") (I.bigint_of_string "5")))) (I.bigint_of_string "0") (I.bigint_of_string "32")) (I.f_gen_slice (I.f_gen_array_load (I.v__Z) (I.f_cvt_bits_uint (I.bigint_of_string "5") (I.extract_bits (v_enc) (I.bigint_of_string "5") (I.bigint_of_string "5")))) (I.bigint_of_string "0") (I.bigint_of_string "16")) (I.f_gen_slice (I.f_gen_array_load (I.v__Z) (I.f_cvt_bits_uint (I.bigint_of_string "5") (I.extract_bits (v_enc) (I.bigint_of_string "16") (I.bigint_of_string "5")))) (I.bigint_of_string "0") (I.bigint_of_string "16")) (I.f_gen_load (I.v_FPCR)));
      I.f_gen_store (v_result__1_1) (I.f_gen_append_bits (I.bigint_of_string "32") (I.bigint_of_string "32") (I.f_gen_slice (I.f_gen_load (v_result__1_1)) (I.bigint_of_string "32") (I.bigint_of_string "32")) (I.f_gen_load (v_Exp102__2)))
    end;
    if I.f_eq_bits (I.bigint_of_string "32") (I.f_and_bits (I.bigint_of_string "32") (v_enc) (I.from_bitsLit "00000000100000000000000000000000")) (I.from_bitsLit "00000000100000000000000000000000") then begin
      let v_Exp110__2 = I.f_decl_bv ("Exp110__2") (I.bigint_of_string "32") in
      I.f_gen_store (v_Exp110__2) (I.f_gen_FPMulAddH (I.bigint_of_string "32") (I.f_gen_slice (I.f_gen_load (v_Exp90__2)) (I.bigint_of_string "32") (I.bigint_of_string "32")) (I.f_gen_append_bits (I.bigint_of_string "1") (I.bigint_of_string "15") (I.f_gen_not_bits (I.bigint_of_string "1") (I.f_gen_slice (I.f_gen_load (v_Exp82__3)) (I.bigint_of_string "31") (I.bigint_of_string "1"))) (I.f_gen_slice (I.f_gen_load (v_Exp82__3)) (I.bigint_of_string "16") (I.bigint_of_string "15"))) (I.f_gen_slice (I.f_gen_load (v_Exp87__3)) (I.bigint_of_string "16") (I.bigint_of_string "16")) (I.f_gen_load (I.v_FPCR)));
      I.f_gen_store (v_result__1_1) (I.f_gen_append_bits (I.bigint_of_string "32") (I.bigint_of_string "32") (I.f_gen_load (v_Exp110__2)) (I.f_gen_slice (I.f_gen_load (v_result__1_1)) (I.bigint_of_string "0") (I.bigint_of_string "32")))
    end else begin
      let v_Exp115__2 = I.f_decl_bv ("Exp115__2") (I.bigint_of_string "32") in
      I.f_gen_store (v_Exp115__2) (I.f_gen_FPMulAddH (I.bigint_of_string "32") (I.f_gen_slice (I.f_gen_load (v_Exp90__2)) (I.bigint_of_string "32") (I.bigint_of_string "32")) (I.f_gen_slice (I.f_gen_load (v_Exp82__3)) (I.bigint_of_string "16") (I.bigint_of_string "16")) (I.f_gen_slice (I.f_gen_load (v_Exp87__3)) (I.bigint_of_string "16") (I.bigint_of_string "16")) (I.f_gen_load (I.v_FPCR)));
      I.f_gen_store (v_result__1_1) (I.f_gen_append_bits (I.bigint_of_string "32") (I.bigint_of_string "32") (I.f_gen_load (v_Exp115__2)) (I.f_gen_slice (I.f_gen_load (v_result__1_1)) (I.bigint_of_string "0") (I.bigint_of_string "32")))
    end;
    I.f_gen_array_store (I.v__Z) (I.f_cvt_bits_uint (I.bigint_of_string "5") (I.extract_bits (v_enc) (I.bigint_of_string "0") (I.bigint_of_string "5"))) (I.f_gen_ZeroExtend (I.bigint_of_string "64") (I.bigint_of_string "128") (I.f_gen_load (v_result__1_1)) (I.f_gen_int_lit (I.bigint_of_string "128")))
  end

