(* AUTO-GENERATED LIFTER FILE *)

open Instruction_building_interface

let f_aarch64_vector_shift_right_narrow_logical (type bitvector) (module I : IBI with type bitvector = bitvector) (v_enc : bitvector) : unit = 
  if I.f_eq_bits (I.bigint_of_string "32") (I.f_and_bits (I.bigint_of_string "32") (v_enc) (I.from_bitsLit "00000000010000000000000000000000")) (I.from_bitsLit "00000000010000000000000000000000") then begin
    failwith "unsupported"
  end else begin
    if I.f_eq_bits (I.bigint_of_string "32") (I.f_and_bits (I.bigint_of_string "32") (v_enc) (I.from_bitsLit "00000000001100000000000000000000")) (I.from_bitsLit "00000000000000000000000000000000") then begin
      let v_Exp10__2 = I.f_decl_bv ("Exp10__2") (I.bigint_of_string "128") in
      I.f_gen_store (v_Exp10__2) (I.f_gen_array_load (I.v__Z) (I.f_cvt_bits_uint (I.bigint_of_string "5") (I.extract_bits (v_enc) (I.bigint_of_string "5") (I.bigint_of_string "5"))));
      let v_If11__1 = ref (I.mkBits (I.bigint_of_string "32") I.bigint_zero) in
      if I.f_eq_bits (I.bigint_of_string "32") (I.f_and_bits (I.bigint_of_string "32") (v_enc) (I.from_bitsLit "00000000000000000000100000000000")) (I.from_bitsLit "00000000000000000000100000000000") then begin
        let v_If13__2 = ref (I.mkBits (I.bigint_of_string "32") I.bigint_zero) in
        v_If13__2 := I.f_ZeroExtend (I.bigint_of_string "16") (I.bigint_of_string "32") (I.f_lsl_bits (I.bigint_of_string "16") (I.bigint_of_string "16") (I.from_bitsLit "0000000000000001") (I.f_sub_bits (I.bigint_of_string "16") (I.f_sub_bits (I.bigint_of_string "16") (I.from_bitsLit "0000000000010000") (I.f_ZeroExtend (I.bigint_of_string "7") (I.bigint_of_string "16") (I.f_append_bits (I.bigint_of_string "4") (I.bigint_of_string "3") (I.extract_bits (v_enc) (I.bigint_of_string "19") (I.bigint_of_string "4")) (I.extract_bits (v_enc) (I.bigint_of_string "16") (I.bigint_of_string "3"))) (I.bigint_of_string "16"))) (I.from_bitsLit "0000000000000001"))) (I.bigint_of_string "32");
        v_If11__1 := !v_If13__2
      end else begin
        v_If11__1 := I.from_bitsLit "00000000000000000000000000000000"
      end;
      let v_If17__2_copyprop = ref (I.undefined ()) in
      v_If17__2_copyprop := I.f_gen_SignExtend (I.bigint_of_string "32") (I.bigint_of_string "143") (I.f_gen_asr_bits (I.bigint_of_string "32") (I.bigint_of_string "16") (I.f_gen_add_bits (I.bigint_of_string "32") (I.f_gen_ZeroExtend (I.bigint_of_string "16") (I.bigint_of_string "32") (I.f_gen_slice (I.f_gen_load (v_Exp10__2)) (I.bigint_of_string "0") (I.bigint_of_string "16")) (I.f_gen_int_lit (I.bigint_of_string "32"))) (I.f_gen_bit_lit (I.bigint_of_string "32") (!v_If11__1))) (I.f_gen_bit_lit (I.bigint_of_string "16") (I.f_sub_bits (I.bigint_of_string "16") (I.from_bitsLit "0000000000010000") (I.f_ZeroExtend (I.bigint_of_string "7") (I.bigint_of_string "16") (I.f_append_bits (I.bigint_of_string "4") (I.bigint_of_string "3") (I.extract_bits (v_enc) (I.bigint_of_string "19") (I.bigint_of_string "4")) (I.extract_bits (v_enc) (I.bigint_of_string "16") (I.bigint_of_string "3"))) (I.bigint_of_string "16"))))) (I.f_gen_int_lit (I.bigint_of_string "143"));
      let v_If23__2_copyprop = ref (I.undefined ()) in
      v_If23__2_copyprop := I.f_gen_SignExtend (I.bigint_of_string "32") (I.bigint_of_string "143") (I.f_gen_asr_bits (I.bigint_of_string "32") (I.bigint_of_string "16") (I.f_gen_add_bits (I.bigint_of_string "32") (I.f_gen_ZeroExtend (I.bigint_of_string "16") (I.bigint_of_string "32") (I.f_gen_slice (I.f_gen_load (v_Exp10__2)) (I.bigint_of_string "16") (I.bigint_of_string "16")) (I.f_gen_int_lit (I.bigint_of_string "32"))) (I.f_gen_bit_lit (I.bigint_of_string "32") (!v_If11__1))) (I.f_gen_bit_lit (I.bigint_of_string "16") (I.f_sub_bits (I.bigint_of_string "16") (I.from_bitsLit "0000000000010000") (I.f_ZeroExtend (I.bigint_of_string "7") (I.bigint_of_string "16") (I.f_append_bits (I.bigint_of_string "4") (I.bigint_of_string "3") (I.extract_bits (v_enc) (I.bigint_of_string "19") (I.bigint_of_string "4")) (I.extract_bits (v_enc) (I.bigint_of_string "16") (I.bigint_of_string "3"))) (I.bigint_of_string "16"))))) (I.f_gen_int_lit (I.bigint_of_string "143"));
      let v_If28__2_copyprop = ref (I.undefined ()) in
      v_If28__2_copyprop := I.f_gen_SignExtend (I.bigint_of_string "32") (I.bigint_of_string "143") (I.f_gen_asr_bits (I.bigint_of_string "32") (I.bigint_of_string "16") (I.f_gen_add_bits (I.bigint_of_string "32") (I.f_gen_ZeroExtend (I.bigint_of_string "16") (I.bigint_of_string "32") (I.f_gen_slice (I.f_gen_load (v_Exp10__2)) (I.bigint_of_string "32") (I.bigint_of_string "16")) (I.f_gen_int_lit (I.bigint_of_string "32"))) (I.f_gen_bit_lit (I.bigint_of_string "32") (!v_If11__1))) (I.f_gen_bit_lit (I.bigint_of_string "16") (I.f_sub_bits (I.bigint_of_string "16") (I.from_bitsLit "0000000000010000") (I.f_ZeroExtend (I.bigint_of_string "7") (I.bigint_of_string "16") (I.f_append_bits (I.bigint_of_string "4") (I.bigint_of_string "3") (I.extract_bits (v_enc) (I.bigint_of_string "19") (I.bigint_of_string "4")) (I.extract_bits (v_enc) (I.bigint_of_string "16") (I.bigint_of_string "3"))) (I.bigint_of_string "16"))))) (I.f_gen_int_lit (I.bigint_of_string "143"));
      let v_If33__2_copyprop = ref (I.undefined ()) in
      v_If33__2_copyprop := I.f_gen_SignExtend (I.bigint_of_string "32") (I.bigint_of_string "143") (I.f_gen_asr_bits (I.bigint_of_string "32") (I.bigint_of_string "16") (I.f_gen_add_bits (I.bigint_of_string "32") (I.f_gen_ZeroExtend (I.bigint_of_string "16") (I.bigint_of_string "32") (I.f_gen_slice (I.f_gen_load (v_Exp10__2)) (I.bigint_of_string "48") (I.bigint_of_string "16")) (I.f_gen_int_lit (I.bigint_of_string "32"))) (I.f_gen_bit_lit (I.bigint_of_string "32") (!v_If11__1))) (I.f_gen_bit_lit (I.bigint_of_string "16") (I.f_sub_bits (I.bigint_of_string "16") (I.from_bitsLit "0000000000010000") (I.f_ZeroExtend (I.bigint_of_string "7") (I.bigint_of_string "16") (I.f_append_bits (I.bigint_of_string "4") (I.bigint_of_string "3") (I.extract_bits (v_enc) (I.bigint_of_string "19") (I.bigint_of_string "4")) (I.extract_bits (v_enc) (I.bigint_of_string "16") (I.bigint_of_string "3"))) (I.bigint_of_string "16"))))) (I.f_gen_int_lit (I.bigint_of_string "143"));
      let v_If38__2_copyprop = ref (I.undefined ()) in
      v_If38__2_copyprop := I.f_gen_SignExtend (I.bigint_of_string "32") (I.bigint_of_string "143") (I.f_gen_asr_bits (I.bigint_of_string "32") (I.bigint_of_string "16") (I.f_gen_add_bits (I.bigint_of_string "32") (I.f_gen_ZeroExtend (I.bigint_of_string "16") (I.bigint_of_string "32") (I.f_gen_slice (I.f_gen_load (v_Exp10__2)) (I.bigint_of_string "64") (I.bigint_of_string "16")) (I.f_gen_int_lit (I.bigint_of_string "32"))) (I.f_gen_bit_lit (I.bigint_of_string "32") (!v_If11__1))) (I.f_gen_bit_lit (I.bigint_of_string "16") (I.f_sub_bits (I.bigint_of_string "16") (I.from_bitsLit "0000000000010000") (I.f_ZeroExtend (I.bigint_of_string "7") (I.bigint_of_string "16") (I.f_append_bits (I.bigint_of_string "4") (I.bigint_of_string "3") (I.extract_bits (v_enc) (I.bigint_of_string "19") (I.bigint_of_string "4")) (I.extract_bits (v_enc) (I.bigint_of_string "16") (I.bigint_of_string "3"))) (I.bigint_of_string "16"))))) (I.f_gen_int_lit (I.bigint_of_string "143"));
      let v_If43__2_copyprop = ref (I.undefined ()) in
      v_If43__2_copyprop := I.f_gen_SignExtend (I.bigint_of_string "32") (I.bigint_of_string "143") (I.f_gen_asr_bits (I.bigint_of_string "32") (I.bigint_of_string "16") (I.f_gen_add_bits (I.bigint_of_string "32") (I.f_gen_ZeroExtend (I.bigint_of_string "16") (I.bigint_of_string "32") (I.f_gen_slice (I.f_gen_load (v_Exp10__2)) (I.bigint_of_string "80") (I.bigint_of_string "16")) (I.f_gen_int_lit (I.bigint_of_string "32"))) (I.f_gen_bit_lit (I.bigint_of_string "32") (!v_If11__1))) (I.f_gen_bit_lit (I.bigint_of_string "16") (I.f_sub_bits (I.bigint_of_string "16") (I.from_bitsLit "0000000000010000") (I.f_ZeroExtend (I.bigint_of_string "7") (I.bigint_of_string "16") (I.f_append_bits (I.bigint_of_string "4") (I.bigint_of_string "3") (I.extract_bits (v_enc) (I.bigint_of_string "19") (I.bigint_of_string "4")) (I.extract_bits (v_enc) (I.bigint_of_string "16") (I.bigint_of_string "3"))) (I.bigint_of_string "16"))))) (I.f_gen_int_lit (I.bigint_of_string "143"));
      let v_If48__2_copyprop = ref (I.undefined ()) in
      v_If48__2_copyprop := I.f_gen_SignExtend (I.bigint_of_string "32") (I.bigint_of_string "143") (I.f_gen_asr_bits (I.bigint_of_string "32") (I.bigint_of_string "16") (I.f_gen_add_bits (I.bigint_of_string "32") (I.f_gen_ZeroExtend (I.bigint_of_string "16") (I.bigint_of_string "32") (I.f_gen_slice (I.f_gen_load (v_Exp10__2)) (I.bigint_of_string "96") (I.bigint_of_string "16")) (I.f_gen_int_lit (I.bigint_of_string "32"))) (I.f_gen_bit_lit (I.bigint_of_string "32") (!v_If11__1))) (I.f_gen_bit_lit (I.bigint_of_string "16") (I.f_sub_bits (I.bigint_of_string "16") (I.from_bitsLit "0000000000010000") (I.f_ZeroExtend (I.bigint_of_string "7") (I.bigint_of_string "16") (I.f_append_bits (I.bigint_of_string "4") (I.bigint_of_string "3") (I.extract_bits (v_enc) (I.bigint_of_string "19") (I.bigint_of_string "4")) (I.extract_bits (v_enc) (I.bigint_of_string "16") (I.bigint_of_string "3"))) (I.bigint_of_string "16"))))) (I.f_gen_int_lit (I.bigint_of_string "143"));
      let v_If53__2_copyprop = ref (I.undefined ()) in
      v_If53__2_copyprop := I.f_gen_SignExtend (I.bigint_of_string "32") (I.bigint_of_string "143") (I.f_gen_asr_bits (I.bigint_of_string "32") (I.bigint_of_string "16") (I.f_gen_add_bits (I.bigint_of_string "32") (I.f_gen_ZeroExtend (I.bigint_of_string "16") (I.bigint_of_string "32") (I.f_gen_slice (I.f_gen_load (v_Exp10__2)) (I.bigint_of_string "112") (I.bigint_of_string "16")) (I.f_gen_int_lit (I.bigint_of_string "32"))) (I.f_gen_bit_lit (I.bigint_of_string "32") (!v_If11__1))) (I.f_gen_bit_lit (I.bigint_of_string "16") (I.f_sub_bits (I.bigint_of_string "16") (I.from_bitsLit "0000000000010000") (I.f_ZeroExtend (I.bigint_of_string "7") (I.bigint_of_string "16") (I.f_append_bits (I.bigint_of_string "4") (I.bigint_of_string "3") (I.extract_bits (v_enc) (I.bigint_of_string "19") (I.bigint_of_string "4")) (I.extract_bits (v_enc) (I.bigint_of_string "16") (I.bigint_of_string "3"))) (I.bigint_of_string "16"))))) (I.f_gen_int_lit (I.bigint_of_string "143"));
      if I.f_eq_bits (I.bigint_of_string "32") (I.f_and_bits (I.bigint_of_string "32") (v_enc) (I.from_bitsLit "01000000000000000000000000000000")) (I.from_bitsLit "00000000000000000000000000000000") then begin
        I.f_gen_array_store (I.v__Z) (I.f_cvt_bits_uint (I.bigint_of_string "5") (I.extract_bits (v_enc) (I.bigint_of_string "0") (I.bigint_of_string "5"))) (I.f_gen_ZeroExtend (I.bigint_of_string "64") (I.bigint_of_string "128") (I.f_gen_append_bits (I.bigint_of_string "8") (I.bigint_of_string "56") (I.f_gen_slice (!v_If53__2_copyprop) (I.bigint_of_string "0") (I.bigint_of_string "8")) (I.f_gen_append_bits (I.bigint_of_string "8") (I.bigint_of_string "48") (I.f_gen_slice (!v_If48__2_copyprop) (I.bigint_of_string "0") (I.bigint_of_string "8")) (I.f_gen_append_bits (I.bigint_of_string "8") (I.bigint_of_string "40") (I.f_gen_slice (!v_If43__2_copyprop) (I.bigint_of_string "0") (I.bigint_of_string "8")) (I.f_gen_append_bits (I.bigint_of_string "8") (I.bigint_of_string "32") (I.f_gen_slice (!v_If38__2_copyprop) (I.bigint_of_string "0") (I.bigint_of_string "8")) (I.f_gen_append_bits (I.bigint_of_string "8") (I.bigint_of_string "24") (I.f_gen_slice (!v_If33__2_copyprop) (I.bigint_of_string "0") (I.bigint_of_string "8")) (I.f_gen_append_bits (I.bigint_of_string "8") (I.bigint_of_string "16") (I.f_gen_slice (!v_If28__2_copyprop) (I.bigint_of_string "0") (I.bigint_of_string "8")) (I.f_gen_append_bits (I.bigint_of_string "8") (I.bigint_of_string "8") (I.f_gen_slice (!v_If23__2_copyprop) (I.bigint_of_string "0") (I.bigint_of_string "8")) (I.f_gen_slice (!v_If17__2_copyprop) (I.bigint_of_string "0") (I.bigint_of_string "8"))))))))) (I.f_gen_int_lit (I.bigint_of_string "128")))
      end else begin
        I.f_gen_array_store (I.v__Z) (I.f_cvt_bits_uint (I.bigint_of_string "5") (I.extract_bits (v_enc) (I.bigint_of_string "0") (I.bigint_of_string "5"))) (I.f_gen_append_bits (I.bigint_of_string "64") (I.bigint_of_string "64") (I.f_gen_append_bits (I.bigint_of_string "8") (I.bigint_of_string "56") (I.f_gen_slice (!v_If53__2_copyprop) (I.bigint_of_string "0") (I.bigint_of_string "8")) (I.f_gen_append_bits (I.bigint_of_string "8") (I.bigint_of_string "48") (I.f_gen_slice (!v_If48__2_copyprop) (I.bigint_of_string "0") (I.bigint_of_string "8")) (I.f_gen_append_bits (I.bigint_of_string "8") (I.bigint_of_string "40") (I.f_gen_slice (!v_If43__2_copyprop) (I.bigint_of_string "0") (I.bigint_of_string "8")) (I.f_gen_append_bits (I.bigint_of_string "8") (I.bigint_of_string "32") (I.f_gen_slice (!v_If38__2_copyprop) (I.bigint_of_string "0") (I.bigint_of_string "8")) (I.f_gen_append_bits (I.bigint_of_string "8") (I.bigint_of_string "24") (I.f_gen_slice (!v_If33__2_copyprop) (I.bigint_of_string "0") (I.bigint_of_string "8")) (I.f_gen_append_bits (I.bigint_of_string "8") (I.bigint_of_string "16") (I.f_gen_slice (!v_If28__2_copyprop) (I.bigint_of_string "0") (I.bigint_of_string "8")) (I.f_gen_append_bits (I.bigint_of_string "8") (I.bigint_of_string "8") (I.f_gen_slice (!v_If23__2_copyprop) (I.bigint_of_string "0") (I.bigint_of_string "8")) (I.f_gen_slice (!v_If17__2_copyprop) (I.bigint_of_string "0") (I.bigint_of_string "8"))))))))) (I.f_gen_slice (I.f_gen_array_load (I.v__Z) (I.f_cvt_bits_uint (I.bigint_of_string "5") (I.extract_bits (v_enc) (I.bigint_of_string "0") (I.bigint_of_string "5")))) (I.bigint_of_string "0") (I.bigint_of_string "64")))
      end
    end else begin
      if I.f_eq_bits (I.bigint_of_string "32") (I.f_and_bits (I.bigint_of_string "32") (v_enc) (I.from_bitsLit "00000000001000000000000000000000")) (I.from_bitsLit "00000000000000000000000000000000") then begin
        let v_Exp78__2 = I.f_decl_bv ("Exp78__2") (I.bigint_of_string "128") in
        I.f_gen_store (v_Exp78__2) (I.f_gen_array_load (I.v__Z) (I.f_cvt_bits_uint (I.bigint_of_string "5") (I.extract_bits (v_enc) (I.bigint_of_string "5") (I.bigint_of_string "5"))));
        let v_If79__1 = ref (I.mkBits (I.bigint_of_string "64") I.bigint_zero) in
        if I.f_eq_bits (I.bigint_of_string "32") (I.f_and_bits (I.bigint_of_string "32") (v_enc) (I.from_bitsLit "00000000000000000000100000000000")) (I.from_bitsLit "00000000000000000000100000000000") then begin
          let v_If81__2 = ref (I.mkBits (I.bigint_of_string "64") I.bigint_zero) in
          v_If81__2 := I.f_ZeroExtend (I.bigint_of_string "32") (I.bigint_of_string "64") (I.f_lsl_bits (I.bigint_of_string "32") (I.bigint_of_string "16") (I.from_bitsLit "00000000000000000000000000000001") (I.f_sub_bits (I.bigint_of_string "16") (I.f_sub_bits (I.bigint_of_string "16") (I.from_bitsLit "0000000000100000") (I.f_ZeroExtend (I.bigint_of_string "7") (I.bigint_of_string "16") (I.f_append_bits (I.bigint_of_string "4") (I.bigint_of_string "3") (I.extract_bits (v_enc) (I.bigint_of_string "19") (I.bigint_of_string "4")) (I.extract_bits (v_enc) (I.bigint_of_string "16") (I.bigint_of_string "3"))) (I.bigint_of_string "16"))) (I.from_bitsLit "0000000000000001"))) (I.bigint_of_string "64");
          v_If79__1 := !v_If81__2
        end else begin
          v_If79__1 := I.from_bitsLit "0000000000000000000000000000000000000000000000000000000000000000"
        end;
        let v_If85__2_copyprop = ref (I.undefined ()) in
        v_If85__2_copyprop := I.f_gen_SignExtend (I.bigint_of_string "64") (I.bigint_of_string "159") (I.f_gen_asr_bits (I.bigint_of_string "64") (I.bigint_of_string "16") (I.f_gen_add_bits (I.bigint_of_string "64") (I.f_gen_ZeroExtend (I.bigint_of_string "32") (I.bigint_of_string "64") (I.f_gen_slice (I.f_gen_load (v_Exp78__2)) (I.bigint_of_string "0") (I.bigint_of_string "32")) (I.f_gen_int_lit (I.bigint_of_string "64"))) (I.f_gen_bit_lit (I.bigint_of_string "64") (!v_If79__1))) (I.f_gen_bit_lit (I.bigint_of_string "16") (I.f_sub_bits (I.bigint_of_string "16") (I.from_bitsLit "0000000000100000") (I.f_ZeroExtend (I.bigint_of_string "7") (I.bigint_of_string "16") (I.f_append_bits (I.bigint_of_string "4") (I.bigint_of_string "3") (I.extract_bits (v_enc) (I.bigint_of_string "19") (I.bigint_of_string "4")) (I.extract_bits (v_enc) (I.bigint_of_string "16") (I.bigint_of_string "3"))) (I.bigint_of_string "16"))))) (I.f_gen_int_lit (I.bigint_of_string "159"));
        let v_If91__2_copyprop = ref (I.undefined ()) in
        v_If91__2_copyprop := I.f_gen_SignExtend (I.bigint_of_string "64") (I.bigint_of_string "159") (I.f_gen_asr_bits (I.bigint_of_string "64") (I.bigint_of_string "16") (I.f_gen_add_bits (I.bigint_of_string "64") (I.f_gen_ZeroExtend (I.bigint_of_string "32") (I.bigint_of_string "64") (I.f_gen_slice (I.f_gen_load (v_Exp78__2)) (I.bigint_of_string "32") (I.bigint_of_string "32")) (I.f_gen_int_lit (I.bigint_of_string "64"))) (I.f_gen_bit_lit (I.bigint_of_string "64") (!v_If79__1))) (I.f_gen_bit_lit (I.bigint_of_string "16") (I.f_sub_bits (I.bigint_of_string "16") (I.from_bitsLit "0000000000100000") (I.f_ZeroExtend (I.bigint_of_string "7") (I.bigint_of_string "16") (I.f_append_bits (I.bigint_of_string "4") (I.bigint_of_string "3") (I.extract_bits (v_enc) (I.bigint_of_string "19") (I.bigint_of_string "4")) (I.extract_bits (v_enc) (I.bigint_of_string "16") (I.bigint_of_string "3"))) (I.bigint_of_string "16"))))) (I.f_gen_int_lit (I.bigint_of_string "159"));
        let v_If96__2_copyprop = ref (I.undefined ()) in
        v_If96__2_copyprop := I.f_gen_SignExtend (I.bigint_of_string "64") (I.bigint_of_string "159") (I.f_gen_asr_bits (I.bigint_of_string "64") (I.bigint_of_string "16") (I.f_gen_add_bits (I.bigint_of_string "64") (I.f_gen_ZeroExtend (I.bigint_of_string "32") (I.bigint_of_string "64") (I.f_gen_slice (I.f_gen_load (v_Exp78__2)) (I.bigint_of_string "64") (I.bigint_of_string "32")) (I.f_gen_int_lit (I.bigint_of_string "64"))) (I.f_gen_bit_lit (I.bigint_of_string "64") (!v_If79__1))) (I.f_gen_bit_lit (I.bigint_of_string "16") (I.f_sub_bits (I.bigint_of_string "16") (I.from_bitsLit "0000000000100000") (I.f_ZeroExtend (I.bigint_of_string "7") (I.bigint_of_string "16") (I.f_append_bits (I.bigint_of_string "4") (I.bigint_of_string "3") (I.extract_bits (v_enc) (I.bigint_of_string "19") (I.bigint_of_string "4")) (I.extract_bits (v_enc) (I.bigint_of_string "16") (I.bigint_of_string "3"))) (I.bigint_of_string "16"))))) (I.f_gen_int_lit (I.bigint_of_string "159"));
        let v_If101__2_copyprop = ref (I.undefined ()) in
        v_If101__2_copyprop := I.f_gen_SignExtend (I.bigint_of_string "64") (I.bigint_of_string "159") (I.f_gen_asr_bits (I.bigint_of_string "64") (I.bigint_of_string "16") (I.f_gen_add_bits (I.bigint_of_string "64") (I.f_gen_ZeroExtend (I.bigint_of_string "32") (I.bigint_of_string "64") (I.f_gen_slice (I.f_gen_load (v_Exp78__2)) (I.bigint_of_string "96") (I.bigint_of_string "32")) (I.f_gen_int_lit (I.bigint_of_string "64"))) (I.f_gen_bit_lit (I.bigint_of_string "64") (!v_If79__1))) (I.f_gen_bit_lit (I.bigint_of_string "16") (I.f_sub_bits (I.bigint_of_string "16") (I.from_bitsLit "0000000000100000") (I.f_ZeroExtend (I.bigint_of_string "7") (I.bigint_of_string "16") (I.f_append_bits (I.bigint_of_string "4") (I.bigint_of_string "3") (I.extract_bits (v_enc) (I.bigint_of_string "19") (I.bigint_of_string "4")) (I.extract_bits (v_enc) (I.bigint_of_string "16") (I.bigint_of_string "3"))) (I.bigint_of_string "16"))))) (I.f_gen_int_lit (I.bigint_of_string "159"));
        if I.f_eq_bits (I.bigint_of_string "32") (I.f_and_bits (I.bigint_of_string "32") (v_enc) (I.from_bitsLit "01000000000000000000000000000000")) (I.from_bitsLit "00000000000000000000000000000000") then begin
          I.f_gen_array_store (I.v__Z) (I.f_cvt_bits_uint (I.bigint_of_string "5") (I.extract_bits (v_enc) (I.bigint_of_string "0") (I.bigint_of_string "5"))) (I.f_gen_ZeroExtend (I.bigint_of_string "64") (I.bigint_of_string "128") (I.f_gen_append_bits (I.bigint_of_string "16") (I.bigint_of_string "48") (I.f_gen_slice (!v_If101__2_copyprop) (I.bigint_of_string "0") (I.bigint_of_string "16")) (I.f_gen_append_bits (I.bigint_of_string "16") (I.bigint_of_string "32") (I.f_gen_slice (!v_If96__2_copyprop) (I.bigint_of_string "0") (I.bigint_of_string "16")) (I.f_gen_append_bits (I.bigint_of_string "16") (I.bigint_of_string "16") (I.f_gen_slice (!v_If91__2_copyprop) (I.bigint_of_string "0") (I.bigint_of_string "16")) (I.f_gen_slice (!v_If85__2_copyprop) (I.bigint_of_string "0") (I.bigint_of_string "16"))))) (I.f_gen_int_lit (I.bigint_of_string "128")))
        end else begin
          I.f_gen_array_store (I.v__Z) (I.f_cvt_bits_uint (I.bigint_of_string "5") (I.extract_bits (v_enc) (I.bigint_of_string "0") (I.bigint_of_string "5"))) (I.f_gen_append_bits (I.bigint_of_string "64") (I.bigint_of_string "64") (I.f_gen_append_bits (I.bigint_of_string "16") (I.bigint_of_string "48") (I.f_gen_slice (!v_If101__2_copyprop) (I.bigint_of_string "0") (I.bigint_of_string "16")) (I.f_gen_append_bits (I.bigint_of_string "16") (I.bigint_of_string "32") (I.f_gen_slice (!v_If96__2_copyprop) (I.bigint_of_string "0") (I.bigint_of_string "16")) (I.f_gen_append_bits (I.bigint_of_string "16") (I.bigint_of_string "16") (I.f_gen_slice (!v_If91__2_copyprop) (I.bigint_of_string "0") (I.bigint_of_string "16")) (I.f_gen_slice (!v_If85__2_copyprop) (I.bigint_of_string "0") (I.bigint_of_string "16"))))) (I.f_gen_slice (I.f_gen_array_load (I.v__Z) (I.f_cvt_bits_uint (I.bigint_of_string "5") (I.extract_bits (v_enc) (I.bigint_of_string "0") (I.bigint_of_string "5")))) (I.bigint_of_string "0") (I.bigint_of_string "64")))
        end
      end else begin
        let v_Exp126__2 = I.f_decl_bv ("Exp126__2") (I.bigint_of_string "128") in
        I.f_gen_store (v_Exp126__2) (I.f_gen_array_load (I.v__Z) (I.f_cvt_bits_uint (I.bigint_of_string "5") (I.extract_bits (v_enc) (I.bigint_of_string "5") (I.bigint_of_string "5"))));
        let v_If127__1 = ref (I.mkBits (I.bigint_of_string "128") I.bigint_zero) in
        if I.f_eq_bits (I.bigint_of_string "32") (I.f_and_bits (I.bigint_of_string "32") (v_enc) (I.from_bitsLit "00000000000000000000100000000000")) (I.from_bitsLit "00000000000000000000100000000000") then begin
          let v_If129__2 = ref (I.mkBits (I.bigint_of_string "128") I.bigint_zero) in
          v_If129__2 := I.f_ZeroExtend (I.bigint_of_string "64") (I.bigint_of_string "128") (I.f_lsl_bits (I.bigint_of_string "64") (I.bigint_of_string "16") (I.from_bitsLit "0000000000000000000000000000000000000000000000000000000000000001") (I.f_sub_bits (I.bigint_of_string "16") (I.f_sub_bits (I.bigint_of_string "16") (I.from_bitsLit "0000000001000000") (I.f_ZeroExtend (I.bigint_of_string "7") (I.bigint_of_string "16") (I.f_append_bits (I.bigint_of_string "4") (I.bigint_of_string "3") (I.extract_bits (v_enc) (I.bigint_of_string "19") (I.bigint_of_string "4")) (I.extract_bits (v_enc) (I.bigint_of_string "16") (I.bigint_of_string "3"))) (I.bigint_of_string "16"))) (I.from_bitsLit "0000000000000001"))) (I.bigint_of_string "128");
          v_If127__1 := !v_If129__2
        end else begin
          v_If127__1 := I.from_bitsLit "00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"
        end;
        let v_If133__2_copyprop = ref (I.undefined ()) in
        v_If133__2_copyprop := I.f_gen_SignExtend (I.bigint_of_string "128") (I.bigint_of_string "191") (I.f_gen_asr_bits (I.bigint_of_string "128") (I.bigint_of_string "16") (I.f_gen_add_bits (I.bigint_of_string "128") (I.f_gen_ZeroExtend (I.bigint_of_string "64") (I.bigint_of_string "128") (I.f_gen_slice (I.f_gen_load (v_Exp126__2)) (I.bigint_of_string "0") (I.bigint_of_string "64")) (I.f_gen_int_lit (I.bigint_of_string "128"))) (I.f_gen_bit_lit (I.bigint_of_string "128") (!v_If127__1))) (I.f_gen_bit_lit (I.bigint_of_string "16") (I.f_sub_bits (I.bigint_of_string "16") (I.from_bitsLit "0000000001000000") (I.f_ZeroExtend (I.bigint_of_string "7") (I.bigint_of_string "16") (I.f_append_bits (I.bigint_of_string "4") (I.bigint_of_string "3") (I.extract_bits (v_enc) (I.bigint_of_string "19") (I.bigint_of_string "4")) (I.extract_bits (v_enc) (I.bigint_of_string "16") (I.bigint_of_string "3"))) (I.bigint_of_string "16"))))) (I.f_gen_int_lit (I.bigint_of_string "191"));
        let v_If139__2_copyprop = ref (I.undefined ()) in
        v_If139__2_copyprop := I.f_gen_SignExtend (I.bigint_of_string "128") (I.bigint_of_string "191") (I.f_gen_asr_bits (I.bigint_of_string "128") (I.bigint_of_string "16") (I.f_gen_add_bits (I.bigint_of_string "128") (I.f_gen_ZeroExtend (I.bigint_of_string "64") (I.bigint_of_string "128") (I.f_gen_slice (I.f_gen_load (v_Exp126__2)) (I.bigint_of_string "64") (I.bigint_of_string "64")) (I.f_gen_int_lit (I.bigint_of_string "128"))) (I.f_gen_bit_lit (I.bigint_of_string "128") (!v_If127__1))) (I.f_gen_bit_lit (I.bigint_of_string "16") (I.f_sub_bits (I.bigint_of_string "16") (I.from_bitsLit "0000000001000000") (I.f_ZeroExtend (I.bigint_of_string "7") (I.bigint_of_string "16") (I.f_append_bits (I.bigint_of_string "4") (I.bigint_of_string "3") (I.extract_bits (v_enc) (I.bigint_of_string "19") (I.bigint_of_string "4")) (I.extract_bits (v_enc) (I.bigint_of_string "16") (I.bigint_of_string "3"))) (I.bigint_of_string "16"))))) (I.f_gen_int_lit (I.bigint_of_string "191"));
        if I.f_eq_bits (I.bigint_of_string "32") (I.f_and_bits (I.bigint_of_string "32") (v_enc) (I.from_bitsLit "01000000000000000000000000000000")) (I.from_bitsLit "00000000000000000000000000000000") then begin
          I.f_gen_array_store (I.v__Z) (I.f_cvt_bits_uint (I.bigint_of_string "5") (I.extract_bits (v_enc) (I.bigint_of_string "0") (I.bigint_of_string "5"))) (I.f_gen_ZeroExtend (I.bigint_of_string "64") (I.bigint_of_string "128") (I.f_gen_append_bits (I.bigint_of_string "32") (I.bigint_of_string "32") (I.f_gen_slice (!v_If139__2_copyprop) (I.bigint_of_string "0") (I.bigint_of_string "32")) (I.f_gen_slice (!v_If133__2_copyprop) (I.bigint_of_string "0") (I.bigint_of_string "32"))) (I.f_gen_int_lit (I.bigint_of_string "128")))
        end else begin
          I.f_gen_array_store (I.v__Z) (I.f_cvt_bits_uint (I.bigint_of_string "5") (I.extract_bits (v_enc) (I.bigint_of_string "0") (I.bigint_of_string "5"))) (I.f_gen_append_bits (I.bigint_of_string "64") (I.bigint_of_string "64") (I.f_gen_append_bits (I.bigint_of_string "32") (I.bigint_of_string "32") (I.f_gen_slice (!v_If139__2_copyprop) (I.bigint_of_string "0") (I.bigint_of_string "32")) (I.f_gen_slice (!v_If133__2_copyprop) (I.bigint_of_string "0") (I.bigint_of_string "32"))) (I.f_gen_slice (I.f_gen_array_load (I.v__Z) (I.f_cvt_bits_uint (I.bigint_of_string "5") (I.extract_bits (v_enc) (I.bigint_of_string "0") (I.bigint_of_string "5")))) (I.bigint_of_string "0") (I.bigint_of_string "64")))
        end
      end
    end
  end

